/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CdnSettingsGeoAclStringArray struct for CdnSettingsGeoAclStringArray
type CdnSettingsGeoAclStringArray struct {
	Values []string `json:"values,omitempty"`
}

// NewCdnSettingsGeoAclStringArray instantiates a new CdnSettingsGeoAclStringArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsGeoAclStringArray() *CdnSettingsGeoAclStringArray {
	this := CdnSettingsGeoAclStringArray{}
	return &this
}

// NewCdnSettingsGeoAclStringArrayWithDefaults instantiates a new CdnSettingsGeoAclStringArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsGeoAclStringArrayWithDefaults() *CdnSettingsGeoAclStringArray {
	this := CdnSettingsGeoAclStringArray{}
	return &this
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *CdnSettingsGeoAclStringArray) GetValues() []string {
	if o == nil || isNil(o.Values) {
		var ret []string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsGeoAclStringArray) GetValuesOk() ([]string, bool) {
	if o == nil || isNil(o.Values) {
    return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *CdnSettingsGeoAclStringArray) HasValues() bool {
	if o != nil && !isNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []string and assigns it to the Values field.
func (o *CdnSettingsGeoAclStringArray) SetValues(v []string) {
	o.Values = v
}

func (o CdnSettingsGeoAclStringArray) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableCdnSettingsGeoAclStringArray struct {
	value *CdnSettingsGeoAclStringArray
	isSet bool
}

func (v NullableCdnSettingsGeoAclStringArray) Get() *CdnSettingsGeoAclStringArray {
	return v.value
}

func (v *NullableCdnSettingsGeoAclStringArray) Set(val *CdnSettingsGeoAclStringArray) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsGeoAclStringArray) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsGeoAclStringArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsGeoAclStringArray(val *CdnSettingsGeoAclStringArray) *NullableCdnSettingsGeoAclStringArray {
	return &NullableCdnSettingsGeoAclStringArray{value: val, isSet: true}
}

func (v NullableCdnSettingsGeoAclStringArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsGeoAclStringArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


