/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnGetCountriesResponseCountry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnGetCountriesResponseCountry{}

// CdnGetCountriesResponseCountry struct for CdnGetCountriesResponseCountry
type CdnGetCountriesResponseCountry struct {
	Code *string `json:"code,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewCdnGetCountriesResponseCountry instantiates a new CdnGetCountriesResponseCountry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnGetCountriesResponseCountry() *CdnGetCountriesResponseCountry {
	this := CdnGetCountriesResponseCountry{}
	return &this
}

// NewCdnGetCountriesResponseCountryWithDefaults instantiates a new CdnGetCountriesResponseCountry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnGetCountriesResponseCountryWithDefaults() *CdnGetCountriesResponseCountry {
	this := CdnGetCountriesResponseCountry{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CdnGetCountriesResponseCountry) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnGetCountriesResponseCountry) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CdnGetCountriesResponseCountry) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CdnGetCountriesResponseCountry) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CdnGetCountriesResponseCountry) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnGetCountriesResponseCountry) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CdnGetCountriesResponseCountry) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CdnGetCountriesResponseCountry) SetName(v string) {
	o.Name = &v
}

func (o CdnGetCountriesResponseCountry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnGetCountriesResponseCountry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCdnGetCountriesResponseCountry struct {
	value *CdnGetCountriesResponseCountry
	isSet bool
}

func (v NullableCdnGetCountriesResponseCountry) Get() *CdnGetCountriesResponseCountry {
	return v.value
}

func (v *NullableCdnGetCountriesResponseCountry) Set(val *CdnGetCountriesResponseCountry) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnGetCountriesResponseCountry) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnGetCountriesResponseCountry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnGetCountriesResponseCountry(val *CdnGetCountriesResponseCountry) *NullableCdnGetCountriesResponseCountry {
	return &NullableCdnGetCountriesResponseCountry{value: val, isSet: true}
}

func (v NullableCdnGetCountriesResponseCountry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnGetCountriesResponseCountry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


