/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CdnSettingsUserAgentAcl struct for CdnSettingsUserAgentAcl
type CdnSettingsUserAgentAcl struct {
	Enable *bool `json:"enable,omitempty"`
	PolicyType *string `json:"policy_type,omitempty"`
	ExceptedUserAgent []string `json:"excepted_user_agent,omitempty"`
}

// NewCdnSettingsUserAgentAcl instantiates a new CdnSettingsUserAgentAcl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsUserAgentAcl() *CdnSettingsUserAgentAcl {
	this := CdnSettingsUserAgentAcl{}
	return &this
}

// NewCdnSettingsUserAgentAclWithDefaults instantiates a new CdnSettingsUserAgentAcl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsUserAgentAclWithDefaults() *CdnSettingsUserAgentAcl {
	this := CdnSettingsUserAgentAcl{}
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *CdnSettingsUserAgentAcl) GetEnable() bool {
	if o == nil || isNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsUserAgentAcl) GetEnableOk() (*bool, bool) {
	if o == nil || isNil(o.Enable) {
    return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *CdnSettingsUserAgentAcl) HasEnable() bool {
	if o != nil && !isNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *CdnSettingsUserAgentAcl) SetEnable(v bool) {
	o.Enable = &v
}

// GetPolicyType returns the PolicyType field value if set, zero value otherwise.
func (o *CdnSettingsUserAgentAcl) GetPolicyType() string {
	if o == nil || isNil(o.PolicyType) {
		var ret string
		return ret
	}
	return *o.PolicyType
}

// GetPolicyTypeOk returns a tuple with the PolicyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsUserAgentAcl) GetPolicyTypeOk() (*string, bool) {
	if o == nil || isNil(o.PolicyType) {
    return nil, false
	}
	return o.PolicyType, true
}

// HasPolicyType returns a boolean if a field has been set.
func (o *CdnSettingsUserAgentAcl) HasPolicyType() bool {
	if o != nil && !isNil(o.PolicyType) {
		return true
	}

	return false
}

// SetPolicyType gets a reference to the given string and assigns it to the PolicyType field.
func (o *CdnSettingsUserAgentAcl) SetPolicyType(v string) {
	o.PolicyType = &v
}

// GetExceptedUserAgent returns the ExceptedUserAgent field value if set, zero value otherwise.
func (o *CdnSettingsUserAgentAcl) GetExceptedUserAgent() []string {
	if o == nil || isNil(o.ExceptedUserAgent) {
		var ret []string
		return ret
	}
	return o.ExceptedUserAgent
}

// GetExceptedUserAgentOk returns a tuple with the ExceptedUserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsUserAgentAcl) GetExceptedUserAgentOk() ([]string, bool) {
	if o == nil || isNil(o.ExceptedUserAgent) {
    return nil, false
	}
	return o.ExceptedUserAgent, true
}

// HasExceptedUserAgent returns a boolean if a field has been set.
func (o *CdnSettingsUserAgentAcl) HasExceptedUserAgent() bool {
	if o != nil && !isNil(o.ExceptedUserAgent) {
		return true
	}

	return false
}

// SetExceptedUserAgent gets a reference to the given []string and assigns it to the ExceptedUserAgent field.
func (o *CdnSettingsUserAgentAcl) SetExceptedUserAgent(v []string) {
	o.ExceptedUserAgent = v
}

func (o CdnSettingsUserAgentAcl) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !isNil(o.PolicyType) {
		toSerialize["policy_type"] = o.PolicyType
	}
	if !isNil(o.ExceptedUserAgent) {
		toSerialize["excepted_user_agent"] = o.ExceptedUserAgent
	}
	return json.Marshal(toSerialize)
}

type NullableCdnSettingsUserAgentAcl struct {
	value *CdnSettingsUserAgentAcl
	isSet bool
}

func (v NullableCdnSettingsUserAgentAcl) Get() *CdnSettingsUserAgentAcl {
	return v.value
}

func (v *NullableCdnSettingsUserAgentAcl) Set(val *CdnSettingsUserAgentAcl) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsUserAgentAcl) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsUserAgentAcl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsUserAgentAcl(val *CdnSettingsUserAgentAcl) *NullableCdnSettingsUserAgentAcl {
	return &NullableCdnSettingsUserAgentAcl{value: val, isSet: true}
}

func (v NullableCdnSettingsUserAgentAcl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsUserAgentAcl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


