/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnSourceDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnSourceDomain{}

// CdnSourceDomain struct for CdnSourceDomain
type CdnSourceDomain struct {
	CdnServiceId *string `json:"cdn_service_id,omitempty"`
	SourceServiceId *string `json:"source_service_id,omitempty"`
	SourceServiceType *string `json:"source_service_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	SourceServiceDisplayName *string `json:"source_service_display_name,omitempty"`
	SourceServiceSlug *string `json:"source_service_slug,omitempty"`
	SourceProtocol *string `json:"source_protocol,omitempty"`
}

// NewCdnSourceDomain instantiates a new CdnSourceDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSourceDomain() *CdnSourceDomain {
	this := CdnSourceDomain{}
	return &this
}

// NewCdnSourceDomainWithDefaults instantiates a new CdnSourceDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSourceDomainWithDefaults() *CdnSourceDomain {
	this := CdnSourceDomain{}
	return &this
}

// GetCdnServiceId returns the CdnServiceId field value if set, zero value otherwise.
func (o *CdnSourceDomain) GetCdnServiceId() string {
	if o == nil || IsNil(o.CdnServiceId) {
		var ret string
		return ret
	}
	return *o.CdnServiceId
}

// GetCdnServiceIdOk returns a tuple with the CdnServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSourceDomain) GetCdnServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.CdnServiceId) {
		return nil, false
	}
	return o.CdnServiceId, true
}

// HasCdnServiceId returns a boolean if a field has been set.
func (o *CdnSourceDomain) HasCdnServiceId() bool {
	if o != nil && !IsNil(o.CdnServiceId) {
		return true
	}

	return false
}

// SetCdnServiceId gets a reference to the given string and assigns it to the CdnServiceId field.
func (o *CdnSourceDomain) SetCdnServiceId(v string) {
	o.CdnServiceId = &v
}

// GetSourceServiceId returns the SourceServiceId field value if set, zero value otherwise.
func (o *CdnSourceDomain) GetSourceServiceId() string {
	if o == nil || IsNil(o.SourceServiceId) {
		var ret string
		return ret
	}
	return *o.SourceServiceId
}

// GetSourceServiceIdOk returns a tuple with the SourceServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSourceDomain) GetSourceServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceServiceId) {
		return nil, false
	}
	return o.SourceServiceId, true
}

// HasSourceServiceId returns a boolean if a field has been set.
func (o *CdnSourceDomain) HasSourceServiceId() bool {
	if o != nil && !IsNil(o.SourceServiceId) {
		return true
	}

	return false
}

// SetSourceServiceId gets a reference to the given string and assigns it to the SourceServiceId field.
func (o *CdnSourceDomain) SetSourceServiceId(v string) {
	o.SourceServiceId = &v
}

// GetSourceServiceType returns the SourceServiceType field value if set, zero value otherwise.
func (o *CdnSourceDomain) GetSourceServiceType() string {
	if o == nil || IsNil(o.SourceServiceType) {
		var ret string
		return ret
	}
	return *o.SourceServiceType
}

// GetSourceServiceTypeOk returns a tuple with the SourceServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSourceDomain) GetSourceServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceServiceType) {
		return nil, false
	}
	return o.SourceServiceType, true
}

// HasSourceServiceType returns a boolean if a field has been set.
func (o *CdnSourceDomain) HasSourceServiceType() bool {
	if o != nil && !IsNil(o.SourceServiceType) {
		return true
	}

	return false
}

// SetSourceServiceType gets a reference to the given string and assigns it to the SourceServiceType field.
func (o *CdnSourceDomain) SetSourceServiceType(v string) {
	o.SourceServiceType = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *CdnSourceDomain) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSourceDomain) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *CdnSourceDomain) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *CdnSourceDomain) SetDomain(v string) {
	o.Domain = &v
}

// GetSourceServiceDisplayName returns the SourceServiceDisplayName field value if set, zero value otherwise.
func (o *CdnSourceDomain) GetSourceServiceDisplayName() string {
	if o == nil || IsNil(o.SourceServiceDisplayName) {
		var ret string
		return ret
	}
	return *o.SourceServiceDisplayName
}

// GetSourceServiceDisplayNameOk returns a tuple with the SourceServiceDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSourceDomain) GetSourceServiceDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceServiceDisplayName) {
		return nil, false
	}
	return o.SourceServiceDisplayName, true
}

// HasSourceServiceDisplayName returns a boolean if a field has been set.
func (o *CdnSourceDomain) HasSourceServiceDisplayName() bool {
	if o != nil && !IsNil(o.SourceServiceDisplayName) {
		return true
	}

	return false
}

// SetSourceServiceDisplayName gets a reference to the given string and assigns it to the SourceServiceDisplayName field.
func (o *CdnSourceDomain) SetSourceServiceDisplayName(v string) {
	o.SourceServiceDisplayName = &v
}

// GetSourceServiceSlug returns the SourceServiceSlug field value if set, zero value otherwise.
func (o *CdnSourceDomain) GetSourceServiceSlug() string {
	if o == nil || IsNil(o.SourceServiceSlug) {
		var ret string
		return ret
	}
	return *o.SourceServiceSlug
}

// GetSourceServiceSlugOk returns a tuple with the SourceServiceSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSourceDomain) GetSourceServiceSlugOk() (*string, bool) {
	if o == nil || IsNil(o.SourceServiceSlug) {
		return nil, false
	}
	return o.SourceServiceSlug, true
}

// HasSourceServiceSlug returns a boolean if a field has been set.
func (o *CdnSourceDomain) HasSourceServiceSlug() bool {
	if o != nil && !IsNil(o.SourceServiceSlug) {
		return true
	}

	return false
}

// SetSourceServiceSlug gets a reference to the given string and assigns it to the SourceServiceSlug field.
func (o *CdnSourceDomain) SetSourceServiceSlug(v string) {
	o.SourceServiceSlug = &v
}

// GetSourceProtocol returns the SourceProtocol field value if set, zero value otherwise.
func (o *CdnSourceDomain) GetSourceProtocol() string {
	if o == nil || IsNil(o.SourceProtocol) {
		var ret string
		return ret
	}
	return *o.SourceProtocol
}

// GetSourceProtocolOk returns a tuple with the SourceProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSourceDomain) GetSourceProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.SourceProtocol) {
		return nil, false
	}
	return o.SourceProtocol, true
}

// HasSourceProtocol returns a boolean if a field has been set.
func (o *CdnSourceDomain) HasSourceProtocol() bool {
	if o != nil && !IsNil(o.SourceProtocol) {
		return true
	}

	return false
}

// SetSourceProtocol gets a reference to the given string and assigns it to the SourceProtocol field.
func (o *CdnSourceDomain) SetSourceProtocol(v string) {
	o.SourceProtocol = &v
}

func (o CdnSourceDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnSourceDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CdnServiceId) {
		toSerialize["cdn_service_id"] = o.CdnServiceId
	}
	if !IsNil(o.SourceServiceId) {
		toSerialize["source_service_id"] = o.SourceServiceId
	}
	if !IsNil(o.SourceServiceType) {
		toSerialize["source_service_type"] = o.SourceServiceType
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.SourceServiceDisplayName) {
		toSerialize["source_service_display_name"] = o.SourceServiceDisplayName
	}
	if !IsNil(o.SourceServiceSlug) {
		toSerialize["source_service_slug"] = o.SourceServiceSlug
	}
	if !IsNil(o.SourceProtocol) {
		toSerialize["source_protocol"] = o.SourceProtocol
	}
	return toSerialize, nil
}

type NullableCdnSourceDomain struct {
	value *CdnSourceDomain
	isSet bool
}

func (v NullableCdnSourceDomain) Get() *CdnSourceDomain {
	return v.value
}

func (v *NullableCdnSourceDomain) Set(val *CdnSourceDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSourceDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSourceDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSourceDomain(val *CdnSourceDomain) *NullableCdnSourceDomain {
	return &NullableCdnSourceDomain{value: val, isSet: true}
}

func (v NullableCdnSourceDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSourceDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


