/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// ProjectUpdateProjectResponseError struct for ProjectUpdateProjectResponseError
type ProjectUpdateProjectResponseError struct {
	Message *string `json:"message,omitempty"`
	Code *string `json:"code,omitempty"`
}

// NewProjectUpdateProjectResponseError instantiates a new ProjectUpdateProjectResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectUpdateProjectResponseError() *ProjectUpdateProjectResponseError {
	this := ProjectUpdateProjectResponseError{}
	return &this
}

// NewProjectUpdateProjectResponseErrorWithDefaults instantiates a new ProjectUpdateProjectResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectUpdateProjectResponseErrorWithDefaults() *ProjectUpdateProjectResponseError {
	this := ProjectUpdateProjectResponseError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ProjectUpdateProjectResponseError) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdateProjectResponseError) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ProjectUpdateProjectResponseError) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ProjectUpdateProjectResponseError) SetMessage(v string) {
	o.Message = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ProjectUpdateProjectResponseError) GetCode() string {
	if o == nil || isNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdateProjectResponseError) GetCodeOk() (*string, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ProjectUpdateProjectResponseError) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ProjectUpdateProjectResponseError) SetCode(v string) {
	o.Code = &v
}

func (o ProjectUpdateProjectResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return json.Marshal(toSerialize)
}

type NullableProjectUpdateProjectResponseError struct {
	value *ProjectUpdateProjectResponseError
	isSet bool
}

func (v NullableProjectUpdateProjectResponseError) Get() *ProjectUpdateProjectResponseError {
	return v.value
}

func (v *NullableProjectUpdateProjectResponseError) Set(val *ProjectUpdateProjectResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectUpdateProjectResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectUpdateProjectResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectUpdateProjectResponseError(val *ProjectUpdateProjectResponseError) *NullableProjectUpdateProjectResponseError {
	return &NullableProjectUpdateProjectResponseError{value: val, isSet: true}
}

func (v NullableProjectUpdateProjectResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectUpdateProjectResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


