/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CdnPreloadCacheByPathsResponse struct for CdnPreloadCacheByPathsResponse
type CdnPreloadCacheByPathsResponse struct {
	Cdn *CdnCdn `json:"cdn,omitempty"`
	Error *CdnPreloadCacheByPathsResponseError `json:"error,omitempty"`
}

// NewCdnPreloadCacheByPathsResponse instantiates a new CdnPreloadCacheByPathsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnPreloadCacheByPathsResponse() *CdnPreloadCacheByPathsResponse {
	this := CdnPreloadCacheByPathsResponse{}
	return &this
}

// NewCdnPreloadCacheByPathsResponseWithDefaults instantiates a new CdnPreloadCacheByPathsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnPreloadCacheByPathsResponseWithDefaults() *CdnPreloadCacheByPathsResponse {
	this := CdnPreloadCacheByPathsResponse{}
	return &this
}

// GetCdn returns the Cdn field value if set, zero value otherwise.
func (o *CdnPreloadCacheByPathsResponse) GetCdn() CdnCdn {
	if o == nil || isNil(o.Cdn) {
		var ret CdnCdn
		return ret
	}
	return *o.Cdn
}

// GetCdnOk returns a tuple with the Cdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnPreloadCacheByPathsResponse) GetCdnOk() (*CdnCdn, bool) {
	if o == nil || isNil(o.Cdn) {
    return nil, false
	}
	return o.Cdn, true
}

// HasCdn returns a boolean if a field has been set.
func (o *CdnPreloadCacheByPathsResponse) HasCdn() bool {
	if o != nil && !isNil(o.Cdn) {
		return true
	}

	return false
}

// SetCdn gets a reference to the given CdnCdn and assigns it to the Cdn field.
func (o *CdnPreloadCacheByPathsResponse) SetCdn(v CdnCdn) {
	o.Cdn = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CdnPreloadCacheByPathsResponse) GetError() CdnPreloadCacheByPathsResponseError {
	if o == nil || isNil(o.Error) {
		var ret CdnPreloadCacheByPathsResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnPreloadCacheByPathsResponse) GetErrorOk() (*CdnPreloadCacheByPathsResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CdnPreloadCacheByPathsResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CdnPreloadCacheByPathsResponseError and assigns it to the Error field.
func (o *CdnPreloadCacheByPathsResponse) SetError(v CdnPreloadCacheByPathsResponseError) {
	o.Error = &v
}

func (o CdnPreloadCacheByPathsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Cdn) {
		toSerialize["cdn"] = o.Cdn
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableCdnPreloadCacheByPathsResponse struct {
	value *CdnPreloadCacheByPathsResponse
	isSet bool
}

func (v NullableCdnPreloadCacheByPathsResponse) Get() *CdnPreloadCacheByPathsResponse {
	return v.value
}

func (v *NullableCdnPreloadCacheByPathsResponse) Set(val *CdnPreloadCacheByPathsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnPreloadCacheByPathsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnPreloadCacheByPathsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnPreloadCacheByPathsResponse(val *CdnPreloadCacheByPathsResponse) *NullableCdnPreloadCacheByPathsResponse {
	return &NullableCdnPreloadCacheByPathsResponse{value: val, isSet: true}
}

func (v NullableCdnPreloadCacheByPathsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnPreloadCacheByPathsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


