/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// MysqlSetConfigRequest struct for MysqlSetConfigRequest
type MysqlSetConfigRequest struct {
	ServiceId *string `json:"service_id,omitempty"`
	Param *map[string]string `json:"param,omitempty"`
	PresetName *string `json:"preset_name,omitempty"`
}

// NewMysqlSetConfigRequest instantiates a new MysqlSetConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlSetConfigRequest() *MysqlSetConfigRequest {
	this := MysqlSetConfigRequest{}
	return &this
}

// NewMysqlSetConfigRequestWithDefaults instantiates a new MysqlSetConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlSetConfigRequestWithDefaults() *MysqlSetConfigRequest {
	this := MysqlSetConfigRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *MysqlSetConfigRequest) GetServiceId() string {
	if o == nil || isNil(o.ServiceId) {
		var ret string
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlSetConfigRequest) GetServiceIdOk() (*string, bool) {
	if o == nil || isNil(o.ServiceId) {
    return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *MysqlSetConfigRequest) HasServiceId() bool {
	if o != nil && !isNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given string and assigns it to the ServiceId field.
func (o *MysqlSetConfigRequest) SetServiceId(v string) {
	o.ServiceId = &v
}

// GetParam returns the Param field value if set, zero value otherwise.
func (o *MysqlSetConfigRequest) GetParam() map[string]string {
	if o == nil || isNil(o.Param) {
		var ret map[string]string
		return ret
	}
	return *o.Param
}

// GetParamOk returns a tuple with the Param field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlSetConfigRequest) GetParamOk() (*map[string]string, bool) {
	if o == nil || isNil(o.Param) {
    return nil, false
	}
	return o.Param, true
}

// HasParam returns a boolean if a field has been set.
func (o *MysqlSetConfigRequest) HasParam() bool {
	if o != nil && !isNil(o.Param) {
		return true
	}

	return false
}

// SetParam gets a reference to the given map[string]string and assigns it to the Param field.
func (o *MysqlSetConfigRequest) SetParam(v map[string]string) {
	o.Param = &v
}

// GetPresetName returns the PresetName field value if set, zero value otherwise.
func (o *MysqlSetConfigRequest) GetPresetName() string {
	if o == nil || isNil(o.PresetName) {
		var ret string
		return ret
	}
	return *o.PresetName
}

// GetPresetNameOk returns a tuple with the PresetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlSetConfigRequest) GetPresetNameOk() (*string, bool) {
	if o == nil || isNil(o.PresetName) {
    return nil, false
	}
	return o.PresetName, true
}

// HasPresetName returns a boolean if a field has been set.
func (o *MysqlSetConfigRequest) HasPresetName() bool {
	if o != nil && !isNil(o.PresetName) {
		return true
	}

	return false
}

// SetPresetName gets a reference to the given string and assigns it to the PresetName field.
func (o *MysqlSetConfigRequest) SetPresetName(v string) {
	o.PresetName = &v
}

func (o MysqlSetConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !isNil(o.Param) {
		toSerialize["param"] = o.Param
	}
	if !isNil(o.PresetName) {
		toSerialize["preset_name"] = o.PresetName
	}
	return json.Marshal(toSerialize)
}

type NullableMysqlSetConfigRequest struct {
	value *MysqlSetConfigRequest
	isSet bool
}

func (v NullableMysqlSetConfigRequest) Get() *MysqlSetConfigRequest {
	return v.value
}

func (v *NullableMysqlSetConfigRequest) Set(val *MysqlSetConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlSetConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlSetConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlSetConfigRequest(val *MysqlSetConfigRequest) *NullableMysqlSetConfigRequest {
	return &NullableMysqlSetConfigRequest{value: val, isSet: true}
}

func (v NullableMysqlSetConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlSetConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


