/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// MysqlStatisticGetNetworkResponse struct for MysqlStatisticGetNetworkResponse
type MysqlStatisticGetNetworkResponse struct {
	DataRx *StructuresStatisticSeriesData `json:"data_rx,omitempty"`
	DataTx *StructuresStatisticSeriesData `json:"data_tx,omitempty"`
	DataRxPrivate *StructuresStatisticSeriesData `json:"data_rx_private,omitempty"`
	DataTxPrivate *StructuresStatisticSeriesData `json:"data_tx_private,omitempty"`
}

// NewMysqlStatisticGetNetworkResponse instantiates a new MysqlStatisticGetNetworkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlStatisticGetNetworkResponse() *MysqlStatisticGetNetworkResponse {
	this := MysqlStatisticGetNetworkResponse{}
	return &this
}

// NewMysqlStatisticGetNetworkResponseWithDefaults instantiates a new MysqlStatisticGetNetworkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlStatisticGetNetworkResponseWithDefaults() *MysqlStatisticGetNetworkResponse {
	this := MysqlStatisticGetNetworkResponse{}
	return &this
}

// GetDataRx returns the DataRx field value if set, zero value otherwise.
func (o *MysqlStatisticGetNetworkResponse) GetDataRx() StructuresStatisticSeriesData {
	if o == nil || isNil(o.DataRx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataRx
}

// GetDataRxOk returns a tuple with the DataRx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlStatisticGetNetworkResponse) GetDataRxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || isNil(o.DataRx) {
    return nil, false
	}
	return o.DataRx, true
}

// HasDataRx returns a boolean if a field has been set.
func (o *MysqlStatisticGetNetworkResponse) HasDataRx() bool {
	if o != nil && !isNil(o.DataRx) {
		return true
	}

	return false
}

// SetDataRx gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataRx field.
func (o *MysqlStatisticGetNetworkResponse) SetDataRx(v StructuresStatisticSeriesData) {
	o.DataRx = &v
}

// GetDataTx returns the DataTx field value if set, zero value otherwise.
func (o *MysqlStatisticGetNetworkResponse) GetDataTx() StructuresStatisticSeriesData {
	if o == nil || isNil(o.DataTx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataTx
}

// GetDataTxOk returns a tuple with the DataTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlStatisticGetNetworkResponse) GetDataTxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || isNil(o.DataTx) {
    return nil, false
	}
	return o.DataTx, true
}

// HasDataTx returns a boolean if a field has been set.
func (o *MysqlStatisticGetNetworkResponse) HasDataTx() bool {
	if o != nil && !isNil(o.DataTx) {
		return true
	}

	return false
}

// SetDataTx gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataTx field.
func (o *MysqlStatisticGetNetworkResponse) SetDataTx(v StructuresStatisticSeriesData) {
	o.DataTx = &v
}

// GetDataRxPrivate returns the DataRxPrivate field value if set, zero value otherwise.
func (o *MysqlStatisticGetNetworkResponse) GetDataRxPrivate() StructuresStatisticSeriesData {
	if o == nil || isNil(o.DataRxPrivate) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataRxPrivate
}

// GetDataRxPrivateOk returns a tuple with the DataRxPrivate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlStatisticGetNetworkResponse) GetDataRxPrivateOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || isNil(o.DataRxPrivate) {
    return nil, false
	}
	return o.DataRxPrivate, true
}

// HasDataRxPrivate returns a boolean if a field has been set.
func (o *MysqlStatisticGetNetworkResponse) HasDataRxPrivate() bool {
	if o != nil && !isNil(o.DataRxPrivate) {
		return true
	}

	return false
}

// SetDataRxPrivate gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataRxPrivate field.
func (o *MysqlStatisticGetNetworkResponse) SetDataRxPrivate(v StructuresStatisticSeriesData) {
	o.DataRxPrivate = &v
}

// GetDataTxPrivate returns the DataTxPrivate field value if set, zero value otherwise.
func (o *MysqlStatisticGetNetworkResponse) GetDataTxPrivate() StructuresStatisticSeriesData {
	if o == nil || isNil(o.DataTxPrivate) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataTxPrivate
}

// GetDataTxPrivateOk returns a tuple with the DataTxPrivate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlStatisticGetNetworkResponse) GetDataTxPrivateOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || isNil(o.DataTxPrivate) {
    return nil, false
	}
	return o.DataTxPrivate, true
}

// HasDataTxPrivate returns a boolean if a field has been set.
func (o *MysqlStatisticGetNetworkResponse) HasDataTxPrivate() bool {
	if o != nil && !isNil(o.DataTxPrivate) {
		return true
	}

	return false
}

// SetDataTxPrivate gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataTxPrivate field.
func (o *MysqlStatisticGetNetworkResponse) SetDataTxPrivate(v StructuresStatisticSeriesData) {
	o.DataTxPrivate = &v
}

func (o MysqlStatisticGetNetworkResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DataRx) {
		toSerialize["data_rx"] = o.DataRx
	}
	if !isNil(o.DataTx) {
		toSerialize["data_tx"] = o.DataTx
	}
	if !isNil(o.DataRxPrivate) {
		toSerialize["data_rx_private"] = o.DataRxPrivate
	}
	if !isNil(o.DataTxPrivate) {
		toSerialize["data_tx_private"] = o.DataTxPrivate
	}
	return json.Marshal(toSerialize)
}

type NullableMysqlStatisticGetNetworkResponse struct {
	value *MysqlStatisticGetNetworkResponse
	isSet bool
}

func (v NullableMysqlStatisticGetNetworkResponse) Get() *MysqlStatisticGetNetworkResponse {
	return v.value
}

func (v *NullableMysqlStatisticGetNetworkResponse) Set(val *MysqlStatisticGetNetworkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlStatisticGetNetworkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlStatisticGetNetworkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlStatisticGetNetworkResponse(val *MysqlStatisticGetNetworkResponse) *NullableMysqlStatisticGetNetworkResponse {
	return &NullableMysqlStatisticGetNetworkResponse{value: val, isSet: true}
}

func (v NullableMysqlStatisticGetNetworkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlStatisticGetNetworkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


