/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnSettingsCors type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnSettingsCors{}

// CdnSettingsCors struct for CdnSettingsCors
type CdnSettingsCors struct {
	Enabled *bool `json:"enabled,omitempty"`
	Value []string `json:"value,omitempty"`
	Always *bool `json:"always,omitempty"`
}

// NewCdnSettingsCors instantiates a new CdnSettingsCors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsCors() *CdnSettingsCors {
	this := CdnSettingsCors{}
	return &this
}

// NewCdnSettingsCorsWithDefaults instantiates a new CdnSettingsCors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsCorsWithDefaults() *CdnSettingsCors {
	this := CdnSettingsCors{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CdnSettingsCors) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsCors) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CdnSettingsCors) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CdnSettingsCors) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CdnSettingsCors) GetValue() []string {
	if o == nil || IsNil(o.Value) {
		var ret []string
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsCors) GetValueOk() ([]string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CdnSettingsCors) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []string and assigns it to the Value field.
func (o *CdnSettingsCors) SetValue(v []string) {
	o.Value = v
}

// GetAlways returns the Always field value if set, zero value otherwise.
func (o *CdnSettingsCors) GetAlways() bool {
	if o == nil || IsNil(o.Always) {
		var ret bool
		return ret
	}
	return *o.Always
}

// GetAlwaysOk returns a tuple with the Always field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsCors) GetAlwaysOk() (*bool, bool) {
	if o == nil || IsNil(o.Always) {
		return nil, false
	}
	return o.Always, true
}

// HasAlways returns a boolean if a field has been set.
func (o *CdnSettingsCors) HasAlways() bool {
	if o != nil && !IsNil(o.Always) {
		return true
	}

	return false
}

// SetAlways gets a reference to the given bool and assigns it to the Always field.
func (o *CdnSettingsCors) SetAlways(v bool) {
	o.Always = &v
}

func (o CdnSettingsCors) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnSettingsCors) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Always) {
		toSerialize["always"] = o.Always
	}
	return toSerialize, nil
}

type NullableCdnSettingsCors struct {
	value *CdnSettingsCors
	isSet bool
}

func (v NullableCdnSettingsCors) Get() *CdnSettingsCors {
	return v.value
}

func (v *NullableCdnSettingsCors) Set(val *CdnSettingsCors) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsCors) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsCors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsCors(val *CdnSettingsCors) *NullableCdnSettingsCors {
	return &NullableCdnSettingsCors{value: val, isSet: true}
}

func (v NullableCdnSettingsCors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsCors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


