/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.4.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CloudRemoveResponse struct for CloudRemoveResponse
type CloudRemoveResponse struct {
	Success map[string]interface{} `json:"success,omitempty"`
}

// NewCloudRemoveResponse instantiates a new CloudRemoveResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudRemoveResponse() *CloudRemoveResponse {
	this := CloudRemoveResponse{}
	return &this
}

// NewCloudRemoveResponseWithDefaults instantiates a new CloudRemoveResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudRemoveResponseWithDefaults() *CloudRemoveResponse {
	this := CloudRemoveResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CloudRemoveResponse) GetSuccess() map[string]interface{} {
	if o == nil || isNil(o.Success) {
		var ret map[string]interface{}
		return ret
	}
	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudRemoveResponse) GetSuccessOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Success) {
    return map[string]interface{}{}, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CloudRemoveResponse) HasSuccess() bool {
	if o != nil && !isNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given map[string]interface{} and assigns it to the Success field.
func (o *CloudRemoveResponse) SetSuccess(v map[string]interface{}) {
	o.Success = v
}

func (o CloudRemoveResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableCloudRemoveResponse struct {
	value *CloudRemoveResponse
	isSet bool
}

func (v NullableCloudRemoveResponse) Get() *CloudRemoveResponse {
	return v.value
}

func (v *NullableCloudRemoveResponse) Set(val *CloudRemoveResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudRemoveResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudRemoveResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudRemoveResponse(val *CloudRemoveResponse) *NullableCloudRemoveResponse {
	return &NullableCloudRemoveResponse{value: val, isSet: true}
}

func (v NullableCloudRemoveResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudRemoveResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


