/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnSettingsResponseHeadersHidingPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnSettingsResponseHeadersHidingPolicy{}

// CdnSettingsResponseHeadersHidingPolicy struct for CdnSettingsResponseHeadersHidingPolicy
type CdnSettingsResponseHeadersHidingPolicy struct {
	Enabled *bool `json:"enabled,omitempty"`
	Excepted []string `json:"excepted,omitempty"`
	Mode *string `json:"mode,omitempty"`
}

// NewCdnSettingsResponseHeadersHidingPolicy instantiates a new CdnSettingsResponseHeadersHidingPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsResponseHeadersHidingPolicy() *CdnSettingsResponseHeadersHidingPolicy {
	this := CdnSettingsResponseHeadersHidingPolicy{}
	return &this
}

// NewCdnSettingsResponseHeadersHidingPolicyWithDefaults instantiates a new CdnSettingsResponseHeadersHidingPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsResponseHeadersHidingPolicyWithDefaults() *CdnSettingsResponseHeadersHidingPolicy {
	this := CdnSettingsResponseHeadersHidingPolicy{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CdnSettingsResponseHeadersHidingPolicy) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsResponseHeadersHidingPolicy) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CdnSettingsResponseHeadersHidingPolicy) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CdnSettingsResponseHeadersHidingPolicy) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetExcepted returns the Excepted field value if set, zero value otherwise.
func (o *CdnSettingsResponseHeadersHidingPolicy) GetExcepted() []string {
	if o == nil || IsNil(o.Excepted) {
		var ret []string
		return ret
	}
	return o.Excepted
}

// GetExceptedOk returns a tuple with the Excepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsResponseHeadersHidingPolicy) GetExceptedOk() ([]string, bool) {
	if o == nil || IsNil(o.Excepted) {
		return nil, false
	}
	return o.Excepted, true
}

// HasExcepted returns a boolean if a field has been set.
func (o *CdnSettingsResponseHeadersHidingPolicy) HasExcepted() bool {
	if o != nil && !IsNil(o.Excepted) {
		return true
	}

	return false
}

// SetExcepted gets a reference to the given []string and assigns it to the Excepted field.
func (o *CdnSettingsResponseHeadersHidingPolicy) SetExcepted(v []string) {
	o.Excepted = v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *CdnSettingsResponseHeadersHidingPolicy) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsResponseHeadersHidingPolicy) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *CdnSettingsResponseHeadersHidingPolicy) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *CdnSettingsResponseHeadersHidingPolicy) SetMode(v string) {
	o.Mode = &v
}

func (o CdnSettingsResponseHeadersHidingPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnSettingsResponseHeadersHidingPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Excepted) {
		toSerialize["excepted"] = o.Excepted
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	return toSerialize, nil
}

type NullableCdnSettingsResponseHeadersHidingPolicy struct {
	value *CdnSettingsResponseHeadersHidingPolicy
	isSet bool
}

func (v NullableCdnSettingsResponseHeadersHidingPolicy) Get() *CdnSettingsResponseHeadersHidingPolicy {
	return v.value
}

func (v *NullableCdnSettingsResponseHeadersHidingPolicy) Set(val *CdnSettingsResponseHeadersHidingPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsResponseHeadersHidingPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsResponseHeadersHidingPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsResponseHeadersHidingPolicy(val *CdnSettingsResponseHeadersHidingPolicy) *NullableCdnSettingsResponseHeadersHidingPolicy {
	return &NullableCdnSettingsResponseHeadersHidingPolicy{value: val, isSet: true}
}

func (v NullableCdnSettingsResponseHeadersHidingPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsResponseHeadersHidingPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


