/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the NetworkDriveMountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkDriveMountResponse{}

// NetworkDriveMountResponse struct for NetworkDriveMountResponse
type NetworkDriveMountResponse struct {
	NetworkDrive *NetworkDriveNetworkDrive `json:"network_drive,omitempty"`
	Error *NetworkDriveMountResponseError `json:"error,omitempty"`
}

// NewNetworkDriveMountResponse instantiates a new NetworkDriveMountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkDriveMountResponse() *NetworkDriveMountResponse {
	this := NetworkDriveMountResponse{}
	return &this
}

// NewNetworkDriveMountResponseWithDefaults instantiates a new NetworkDriveMountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkDriveMountResponseWithDefaults() *NetworkDriveMountResponse {
	this := NetworkDriveMountResponse{}
	return &this
}

// GetNetworkDrive returns the NetworkDrive field value if set, zero value otherwise.
func (o *NetworkDriveMountResponse) GetNetworkDrive() NetworkDriveNetworkDrive {
	if o == nil || IsNil(o.NetworkDrive) {
		var ret NetworkDriveNetworkDrive
		return ret
	}
	return *o.NetworkDrive
}

// GetNetworkDriveOk returns a tuple with the NetworkDrive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveMountResponse) GetNetworkDriveOk() (*NetworkDriveNetworkDrive, bool) {
	if o == nil || IsNil(o.NetworkDrive) {
		return nil, false
	}
	return o.NetworkDrive, true
}

// HasNetworkDrive returns a boolean if a field has been set.
func (o *NetworkDriveMountResponse) HasNetworkDrive() bool {
	if o != nil && !IsNil(o.NetworkDrive) {
		return true
	}

	return false
}

// SetNetworkDrive gets a reference to the given NetworkDriveNetworkDrive and assigns it to the NetworkDrive field.
func (o *NetworkDriveMountResponse) SetNetworkDrive(v NetworkDriveNetworkDrive) {
	o.NetworkDrive = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *NetworkDriveMountResponse) GetError() NetworkDriveMountResponseError {
	if o == nil || IsNil(o.Error) {
		var ret NetworkDriveMountResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveMountResponse) GetErrorOk() (*NetworkDriveMountResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *NetworkDriveMountResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given NetworkDriveMountResponseError and assigns it to the Error field.
func (o *NetworkDriveMountResponse) SetError(v NetworkDriveMountResponseError) {
	o.Error = &v
}

func (o NetworkDriveMountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkDriveMountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkDrive) {
		toSerialize["network_drive"] = o.NetworkDrive
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableNetworkDriveMountResponse struct {
	value *NetworkDriveMountResponse
	isSet bool
}

func (v NullableNetworkDriveMountResponse) Get() *NetworkDriveMountResponse {
	return v.value
}

func (v *NullableNetworkDriveMountResponse) Set(val *NetworkDriveMountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkDriveMountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkDriveMountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkDriveMountResponse(val *NetworkDriveMountResponse) *NullableNetworkDriveMountResponse {
	return &NullableNetworkDriveMountResponse{value: val, isSet: true}
}

func (v NullableNetworkDriveMountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkDriveMountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


