/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the NetworkDriveUnmountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkDriveUnmountResponse{}

// NetworkDriveUnmountResponse struct for NetworkDriveUnmountResponse
type NetworkDriveUnmountResponse struct {
	NetworkDrive *NetworkDriveNetworkDrive `json:"network_drive,omitempty"`
	Error *NetworkDriveUnmountResponseError `json:"error,omitempty"`
}

// NewNetworkDriveUnmountResponse instantiates a new NetworkDriveUnmountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkDriveUnmountResponse() *NetworkDriveUnmountResponse {
	this := NetworkDriveUnmountResponse{}
	return &this
}

// NewNetworkDriveUnmountResponseWithDefaults instantiates a new NetworkDriveUnmountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkDriveUnmountResponseWithDefaults() *NetworkDriveUnmountResponse {
	this := NetworkDriveUnmountResponse{}
	return &this
}

// GetNetworkDrive returns the NetworkDrive field value if set, zero value otherwise.
func (o *NetworkDriveUnmountResponse) GetNetworkDrive() NetworkDriveNetworkDrive {
	if o == nil || IsNil(o.NetworkDrive) {
		var ret NetworkDriveNetworkDrive
		return ret
	}
	return *o.NetworkDrive
}

// GetNetworkDriveOk returns a tuple with the NetworkDrive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveUnmountResponse) GetNetworkDriveOk() (*NetworkDriveNetworkDrive, bool) {
	if o == nil || IsNil(o.NetworkDrive) {
		return nil, false
	}
	return o.NetworkDrive, true
}

// HasNetworkDrive returns a boolean if a field has been set.
func (o *NetworkDriveUnmountResponse) HasNetworkDrive() bool {
	if o != nil && !IsNil(o.NetworkDrive) {
		return true
	}

	return false
}

// SetNetworkDrive gets a reference to the given NetworkDriveNetworkDrive and assigns it to the NetworkDrive field.
func (o *NetworkDriveUnmountResponse) SetNetworkDrive(v NetworkDriveNetworkDrive) {
	o.NetworkDrive = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *NetworkDriveUnmountResponse) GetError() NetworkDriveUnmountResponseError {
	if o == nil || IsNil(o.Error) {
		var ret NetworkDriveUnmountResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveUnmountResponse) GetErrorOk() (*NetworkDriveUnmountResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *NetworkDriveUnmountResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given NetworkDriveUnmountResponseError and assigns it to the Error field.
func (o *NetworkDriveUnmountResponse) SetError(v NetworkDriveUnmountResponseError) {
	o.Error = &v
}

func (o NetworkDriveUnmountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkDriveUnmountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkDrive) {
		toSerialize["network_drive"] = o.NetworkDrive
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableNetworkDriveUnmountResponse struct {
	value *NetworkDriveUnmountResponse
	isSet bool
}

func (v NullableNetworkDriveUnmountResponse) Get() *NetworkDriveUnmountResponse {
	return v.value
}

func (v *NullableNetworkDriveUnmountResponse) Set(val *NetworkDriveUnmountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkDriveUnmountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkDriveUnmountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkDriveUnmountResponse(val *NetworkDriveUnmountResponse) *NullableNetworkDriveUnmountResponse {
	return &NullableNetworkDriveUnmountResponse{value: val, isSet: true}
}

func (v NullableNetworkDriveUnmountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkDriveUnmountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


