/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// StructuresParamConfigSetValue struct for StructuresParamConfigSetValue
type StructuresParamConfigSetValue struct {
	Value []string `json:"value,omitempty"`
}

// NewStructuresParamConfigSetValue instantiates a new StructuresParamConfigSetValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructuresParamConfigSetValue() *StructuresParamConfigSetValue {
	this := StructuresParamConfigSetValue{}
	return &this
}

// NewStructuresParamConfigSetValueWithDefaults instantiates a new StructuresParamConfigSetValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructuresParamConfigSetValueWithDefaults() *StructuresParamConfigSetValue {
	this := StructuresParamConfigSetValue{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *StructuresParamConfigSetValue) GetValue() []string {
	if o == nil || isNil(o.Value) {
		var ret []string
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructuresParamConfigSetValue) GetValueOk() ([]string, bool) {
	if o == nil || isNil(o.Value) {
    return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *StructuresParamConfigSetValue) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []string and assigns it to the Value field.
func (o *StructuresParamConfigSetValue) SetValue(v []string) {
	o.Value = v
}

func (o StructuresParamConfigSetValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableStructuresParamConfigSetValue struct {
	value *StructuresParamConfigSetValue
	isSet bool
}

func (v NullableStructuresParamConfigSetValue) Get() *StructuresParamConfigSetValue {
	return v.value
}

func (v *NullableStructuresParamConfigSetValue) Set(val *StructuresParamConfigSetValue) {
	v.value = val
	v.isSet = true
}

func (v NullableStructuresParamConfigSetValue) IsSet() bool {
	return v.isSet
}

func (v *NullableStructuresParamConfigSetValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructuresParamConfigSetValue(val *StructuresParamConfigSetValue) *NullableStructuresParamConfigSetValue {
	return &NullableStructuresParamConfigSetValue{value: val, isSet: true}
}

func (v NullableStructuresParamConfigSetValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructuresParamConfigSetValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


