/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the NetworkDriveNetworkDrive type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkDriveNetworkDrive{}

// NetworkDriveNetworkDrive struct for NetworkDriveNetworkDrive
type NetworkDriveNetworkDrive struct {
	Id *string `json:"id,omitempty"`
	Size *int32 `json:"size,omitempty"`
	StorageClass *string `json:"storage_class,omitempty"`
	MountedResource *NetworkDriveNetworkDriveMountedResource `json:"mounted_resource,omitempty"`
}

// NewNetworkDriveNetworkDrive instantiates a new NetworkDriveNetworkDrive object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkDriveNetworkDrive() *NetworkDriveNetworkDrive {
	this := NetworkDriveNetworkDrive{}
	return &this
}

// NewNetworkDriveNetworkDriveWithDefaults instantiates a new NetworkDriveNetworkDrive object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkDriveNetworkDriveWithDefaults() *NetworkDriveNetworkDrive {
	this := NetworkDriveNetworkDrive{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NetworkDriveNetworkDrive) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveNetworkDrive) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NetworkDriveNetworkDrive) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NetworkDriveNetworkDrive) SetId(v string) {
	o.Id = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *NetworkDriveNetworkDrive) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveNetworkDrive) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *NetworkDriveNetworkDrive) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *NetworkDriveNetworkDrive) SetSize(v int32) {
	o.Size = &v
}

// GetStorageClass returns the StorageClass field value if set, zero value otherwise.
func (o *NetworkDriveNetworkDrive) GetStorageClass() string {
	if o == nil || IsNil(o.StorageClass) {
		var ret string
		return ret
	}
	return *o.StorageClass
}

// GetStorageClassOk returns a tuple with the StorageClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveNetworkDrive) GetStorageClassOk() (*string, bool) {
	if o == nil || IsNil(o.StorageClass) {
		return nil, false
	}
	return o.StorageClass, true
}

// HasStorageClass returns a boolean if a field has been set.
func (o *NetworkDriveNetworkDrive) HasStorageClass() bool {
	if o != nil && !IsNil(o.StorageClass) {
		return true
	}

	return false
}

// SetStorageClass gets a reference to the given string and assigns it to the StorageClass field.
func (o *NetworkDriveNetworkDrive) SetStorageClass(v string) {
	o.StorageClass = &v
}

// GetMountedResource returns the MountedResource field value if set, zero value otherwise.
func (o *NetworkDriveNetworkDrive) GetMountedResource() NetworkDriveNetworkDriveMountedResource {
	if o == nil || IsNil(o.MountedResource) {
		var ret NetworkDriveNetworkDriveMountedResource
		return ret
	}
	return *o.MountedResource
}

// GetMountedResourceOk returns a tuple with the MountedResource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveNetworkDrive) GetMountedResourceOk() (*NetworkDriveNetworkDriveMountedResource, bool) {
	if o == nil || IsNil(o.MountedResource) {
		return nil, false
	}
	return o.MountedResource, true
}

// HasMountedResource returns a boolean if a field has been set.
func (o *NetworkDriveNetworkDrive) HasMountedResource() bool {
	if o != nil && !IsNil(o.MountedResource) {
		return true
	}

	return false
}

// SetMountedResource gets a reference to the given NetworkDriveNetworkDriveMountedResource and assigns it to the MountedResource field.
func (o *NetworkDriveNetworkDrive) SetMountedResource(v NetworkDriveNetworkDriveMountedResource) {
	o.MountedResource = &v
}

func (o NetworkDriveNetworkDrive) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkDriveNetworkDrive) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.StorageClass) {
		toSerialize["storage_class"] = o.StorageClass
	}
	if !IsNil(o.MountedResource) {
		toSerialize["mounted_resource"] = o.MountedResource
	}
	return toSerialize, nil
}

type NullableNetworkDriveNetworkDrive struct {
	value *NetworkDriveNetworkDrive
	isSet bool
}

func (v NullableNetworkDriveNetworkDrive) Get() *NetworkDriveNetworkDrive {
	return v.value
}

func (v *NullableNetworkDriveNetworkDrive) Set(val *NetworkDriveNetworkDrive) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkDriveNetworkDrive) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkDriveNetworkDrive) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkDriveNetworkDrive(val *NetworkDriveNetworkDrive) *NullableNetworkDriveNetworkDrive {
	return &NullableNetworkDriveNetworkDrive{value: val, isSet: true}
}

func (v NullableNetworkDriveNetworkDrive) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkDriveNetworkDrive) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


