/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnSettingsCachingTimeBrowser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnSettingsCachingTimeBrowser{}

// CdnSettingsCachingTimeBrowser struct for CdnSettingsCachingTimeBrowser
type CdnSettingsCachingTimeBrowser struct {
	Enable *bool `json:"enable,omitempty"`
	Type *string `json:"type,omitempty"`
	Time *int32 `json:"time,omitempty"`
}

// NewCdnSettingsCachingTimeBrowser instantiates a new CdnSettingsCachingTimeBrowser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsCachingTimeBrowser() *CdnSettingsCachingTimeBrowser {
	this := CdnSettingsCachingTimeBrowser{}
	return &this
}

// NewCdnSettingsCachingTimeBrowserWithDefaults instantiates a new CdnSettingsCachingTimeBrowser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsCachingTimeBrowserWithDefaults() *CdnSettingsCachingTimeBrowser {
	this := CdnSettingsCachingTimeBrowser{}
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *CdnSettingsCachingTimeBrowser) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsCachingTimeBrowser) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *CdnSettingsCachingTimeBrowser) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *CdnSettingsCachingTimeBrowser) SetEnable(v bool) {
	o.Enable = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CdnSettingsCachingTimeBrowser) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsCachingTimeBrowser) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CdnSettingsCachingTimeBrowser) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CdnSettingsCachingTimeBrowser) SetType(v string) {
	o.Type = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *CdnSettingsCachingTimeBrowser) GetTime() int32 {
	if o == nil || IsNil(o.Time) {
		var ret int32
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsCachingTimeBrowser) GetTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *CdnSettingsCachingTimeBrowser) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given int32 and assigns it to the Time field.
func (o *CdnSettingsCachingTimeBrowser) SetTime(v int32) {
	o.Time = &v
}

func (o CdnSettingsCachingTimeBrowser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnSettingsCachingTimeBrowser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableCdnSettingsCachingTimeBrowser struct {
	value *CdnSettingsCachingTimeBrowser
	isSet bool
}

func (v NullableCdnSettingsCachingTimeBrowser) Get() *CdnSettingsCachingTimeBrowser {
	return v.value
}

func (v *NullableCdnSettingsCachingTimeBrowser) Set(val *CdnSettingsCachingTimeBrowser) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsCachingTimeBrowser) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsCachingTimeBrowser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsCachingTimeBrowser(val *CdnSettingsCachingTimeBrowser) *NullableCdnSettingsCachingTimeBrowser {
	return &NullableCdnSettingsCachingTimeBrowser{value: val, isSet: true}
}

func (v NullableCdnSettingsCachingTimeBrowser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsCachingTimeBrowser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


