/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the S3StatisticGetTrafficResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3StatisticGetTrafficResponse{}

// S3StatisticGetTrafficResponse struct for S3StatisticGetTrafficResponse
type S3StatisticGetTrafficResponse struct {
	DataRx *StructuresStatisticSeriesData `json:"data_rx,omitempty"`
	DataTx *StructuresStatisticSeriesData `json:"data_tx,omitempty"`
}

// NewS3StatisticGetTrafficResponse instantiates a new S3StatisticGetTrafficResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3StatisticGetTrafficResponse() *S3StatisticGetTrafficResponse {
	this := S3StatisticGetTrafficResponse{}
	return &this
}

// NewS3StatisticGetTrafficResponseWithDefaults instantiates a new S3StatisticGetTrafficResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3StatisticGetTrafficResponseWithDefaults() *S3StatisticGetTrafficResponse {
	this := S3StatisticGetTrafficResponse{}
	return &this
}

// GetDataRx returns the DataRx field value if set, zero value otherwise.
func (o *S3StatisticGetTrafficResponse) GetDataRx() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.DataRx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataRx
}

// GetDataRxOk returns a tuple with the DataRx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3StatisticGetTrafficResponse) GetDataRxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.DataRx) {
		return nil, false
	}
	return o.DataRx, true
}

// HasDataRx returns a boolean if a field has been set.
func (o *S3StatisticGetTrafficResponse) HasDataRx() bool {
	if o != nil && !IsNil(o.DataRx) {
		return true
	}

	return false
}

// SetDataRx gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataRx field.
func (o *S3StatisticGetTrafficResponse) SetDataRx(v StructuresStatisticSeriesData) {
	o.DataRx = &v
}

// GetDataTx returns the DataTx field value if set, zero value otherwise.
func (o *S3StatisticGetTrafficResponse) GetDataTx() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.DataTx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataTx
}

// GetDataTxOk returns a tuple with the DataTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3StatisticGetTrafficResponse) GetDataTxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.DataTx) {
		return nil, false
	}
	return o.DataTx, true
}

// HasDataTx returns a boolean if a field has been set.
func (o *S3StatisticGetTrafficResponse) HasDataTx() bool {
	if o != nil && !IsNil(o.DataTx) {
		return true
	}

	return false
}

// SetDataTx gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataTx field.
func (o *S3StatisticGetTrafficResponse) SetDataTx(v StructuresStatisticSeriesData) {
	o.DataTx = &v
}

func (o S3StatisticGetTrafficResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3StatisticGetTrafficResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataRx) {
		toSerialize["data_rx"] = o.DataRx
	}
	if !IsNil(o.DataTx) {
		toSerialize["data_tx"] = o.DataTx
	}
	return toSerialize, nil
}

type NullableS3StatisticGetTrafficResponse struct {
	value *S3StatisticGetTrafficResponse
	isSet bool
}

func (v NullableS3StatisticGetTrafficResponse) Get() *S3StatisticGetTrafficResponse {
	return v.value
}

func (v *NullableS3StatisticGetTrafficResponse) Set(val *S3StatisticGetTrafficResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableS3StatisticGetTrafficResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableS3StatisticGetTrafficResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3StatisticGetTrafficResponse(val *S3StatisticGetTrafficResponse) *NullableS3StatisticGetTrafficResponse {
	return &NullableS3StatisticGetTrafficResponse{value: val, isSet: true}
}

func (v NullableS3StatisticGetTrafficResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3StatisticGetTrafficResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


