/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the PostgresqlPostgresql164 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostgresqlPostgresql164{}

// PostgresqlPostgresql164 struct for PostgresqlPostgresql164
type PostgresqlPostgresql164 struct {
	Configuration *PostgresqlPostgresql164Configuration `json:"configuration,omitempty"`
	Host *string `json:"host,omitempty"`
	Port *int32 `json:"port,omitempty"`
	AddressInfo *StructuresAddressInfo `json:"address_info,omitempty"`
	WebuiUrl *string `json:"webui_url,omitempty"`
	DiskUsed *string `json:"disk_used,omitempty"`
	DiskLeft *string `json:"disk_left,omitempty"`
	ReadOnly *bool `json:"read_only,omitempty"`
	WebuiInstalling *bool `json:"webui_installing,omitempty"`
}

// NewPostgresqlPostgresql164 instantiates a new PostgresqlPostgresql164 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostgresqlPostgresql164() *PostgresqlPostgresql164 {
	this := PostgresqlPostgresql164{}
	return &this
}

// NewPostgresqlPostgresql164WithDefaults instantiates a new PostgresqlPostgresql164 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostgresqlPostgresql164WithDefaults() *PostgresqlPostgresql164 {
	this := PostgresqlPostgresql164{}
	return &this
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetConfiguration() PostgresqlPostgresql164Configuration {
	if o == nil || IsNil(o.Configuration) {
		var ret PostgresqlPostgresql164Configuration
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetConfigurationOk() (*PostgresqlPostgresql164Configuration, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given PostgresqlPostgresql164Configuration and assigns it to the Configuration field.
func (o *PostgresqlPostgresql164) SetConfiguration(v PostgresqlPostgresql164Configuration) {
	o.Configuration = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *PostgresqlPostgresql164) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *PostgresqlPostgresql164) SetPort(v int32) {
	o.Port = &v
}

// GetAddressInfo returns the AddressInfo field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetAddressInfo() StructuresAddressInfo {
	if o == nil || IsNil(o.AddressInfo) {
		var ret StructuresAddressInfo
		return ret
	}
	return *o.AddressInfo
}

// GetAddressInfoOk returns a tuple with the AddressInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetAddressInfoOk() (*StructuresAddressInfo, bool) {
	if o == nil || IsNil(o.AddressInfo) {
		return nil, false
	}
	return o.AddressInfo, true
}

// HasAddressInfo returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasAddressInfo() bool {
	if o != nil && !IsNil(o.AddressInfo) {
		return true
	}

	return false
}

// SetAddressInfo gets a reference to the given StructuresAddressInfo and assigns it to the AddressInfo field.
func (o *PostgresqlPostgresql164) SetAddressInfo(v StructuresAddressInfo) {
	o.AddressInfo = &v
}

// GetWebuiUrl returns the WebuiUrl field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetWebuiUrl() string {
	if o == nil || IsNil(o.WebuiUrl) {
		var ret string
		return ret
	}
	return *o.WebuiUrl
}

// GetWebuiUrlOk returns a tuple with the WebuiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetWebuiUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebuiUrl) {
		return nil, false
	}
	return o.WebuiUrl, true
}

// HasWebuiUrl returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasWebuiUrl() bool {
	if o != nil && !IsNil(o.WebuiUrl) {
		return true
	}

	return false
}

// SetWebuiUrl gets a reference to the given string and assigns it to the WebuiUrl field.
func (o *PostgresqlPostgresql164) SetWebuiUrl(v string) {
	o.WebuiUrl = &v
}

// GetDiskUsed returns the DiskUsed field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetDiskUsed() string {
	if o == nil || IsNil(o.DiskUsed) {
		var ret string
		return ret
	}
	return *o.DiskUsed
}

// GetDiskUsedOk returns a tuple with the DiskUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetDiskUsedOk() (*string, bool) {
	if o == nil || IsNil(o.DiskUsed) {
		return nil, false
	}
	return o.DiskUsed, true
}

// HasDiskUsed returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasDiskUsed() bool {
	if o != nil && !IsNil(o.DiskUsed) {
		return true
	}

	return false
}

// SetDiskUsed gets a reference to the given string and assigns it to the DiskUsed field.
func (o *PostgresqlPostgresql164) SetDiskUsed(v string) {
	o.DiskUsed = &v
}

// GetDiskLeft returns the DiskLeft field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetDiskLeft() string {
	if o == nil || IsNil(o.DiskLeft) {
		var ret string
		return ret
	}
	return *o.DiskLeft
}

// GetDiskLeftOk returns a tuple with the DiskLeft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetDiskLeftOk() (*string, bool) {
	if o == nil || IsNil(o.DiskLeft) {
		return nil, false
	}
	return o.DiskLeft, true
}

// HasDiskLeft returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasDiskLeft() bool {
	if o != nil && !IsNil(o.DiskLeft) {
		return true
	}

	return false
}

// SetDiskLeft gets a reference to the given string and assigns it to the DiskLeft field.
func (o *PostgresqlPostgresql164) SetDiskLeft(v string) {
	o.DiskLeft = &v
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetReadOnly() bool {
	if o == nil || IsNil(o.ReadOnly) {
		var ret bool
		return ret
	}
	return *o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetReadOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.ReadOnly) {
		return nil, false
	}
	return o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasReadOnly() bool {
	if o != nil && !IsNil(o.ReadOnly) {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given bool and assigns it to the ReadOnly field.
func (o *PostgresqlPostgresql164) SetReadOnly(v bool) {
	o.ReadOnly = &v
}

// GetWebuiInstalling returns the WebuiInstalling field value if set, zero value otherwise.
func (o *PostgresqlPostgresql164) GetWebuiInstalling() bool {
	if o == nil || IsNil(o.WebuiInstalling) {
		var ret bool
		return ret
	}
	return *o.WebuiInstalling
}

// GetWebuiInstallingOk returns a tuple with the WebuiInstalling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostgresqlPostgresql164) GetWebuiInstallingOk() (*bool, bool) {
	if o == nil || IsNil(o.WebuiInstalling) {
		return nil, false
	}
	return o.WebuiInstalling, true
}

// HasWebuiInstalling returns a boolean if a field has been set.
func (o *PostgresqlPostgresql164) HasWebuiInstalling() bool {
	if o != nil && !IsNil(o.WebuiInstalling) {
		return true
	}

	return false
}

// SetWebuiInstalling gets a reference to the given bool and assigns it to the WebuiInstalling field.
func (o *PostgresqlPostgresql164) SetWebuiInstalling(v bool) {
	o.WebuiInstalling = &v
}

func (o PostgresqlPostgresql164) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostgresqlPostgresql164) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.AddressInfo) {
		toSerialize["address_info"] = o.AddressInfo
	}
	if !IsNil(o.WebuiUrl) {
		toSerialize["webui_url"] = o.WebuiUrl
	}
	if !IsNil(o.DiskUsed) {
		toSerialize["disk_used"] = o.DiskUsed
	}
	if !IsNil(o.DiskLeft) {
		toSerialize["disk_left"] = o.DiskLeft
	}
	if !IsNil(o.ReadOnly) {
		toSerialize["read_only"] = o.ReadOnly
	}
	if !IsNil(o.WebuiInstalling) {
		toSerialize["webui_installing"] = o.WebuiInstalling
	}
	return toSerialize, nil
}

type NullablePostgresqlPostgresql164 struct {
	value *PostgresqlPostgresql164
	isSet bool
}

func (v NullablePostgresqlPostgresql164) Get() *PostgresqlPostgresql164 {
	return v.value
}

func (v *NullablePostgresqlPostgresql164) Set(val *PostgresqlPostgresql164) {
	v.value = val
	v.isSet = true
}

func (v NullablePostgresqlPostgresql164) IsSet() bool {
	return v.isSet
}

func (v *NullablePostgresqlPostgresql164) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostgresqlPostgresql164(val *PostgresqlPostgresql164) *NullablePostgresqlPostgresql164 {
	return &NullablePostgresqlPostgresql164{value: val, isSet: true}
}

func (v NullablePostgresqlPostgresql164) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostgresqlPostgresql164) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


