/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// S3StatisticGetNetworkResponse struct for S3StatisticGetNetworkResponse
type S3StatisticGetNetworkResponse struct {
	DataRx *StructuresStatisticSeriesData `json:"data_rx,omitempty"`
	DataTx *StructuresStatisticSeriesData `json:"data_tx,omitempty"`
}

// NewS3StatisticGetNetworkResponse instantiates a new S3StatisticGetNetworkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3StatisticGetNetworkResponse() *S3StatisticGetNetworkResponse {
	this := S3StatisticGetNetworkResponse{}
	return &this
}

// NewS3StatisticGetNetworkResponseWithDefaults instantiates a new S3StatisticGetNetworkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3StatisticGetNetworkResponseWithDefaults() *S3StatisticGetNetworkResponse {
	this := S3StatisticGetNetworkResponse{}
	return &this
}

// GetDataRx returns the DataRx field value if set, zero value otherwise.
func (o *S3StatisticGetNetworkResponse) GetDataRx() StructuresStatisticSeriesData {
	if o == nil || isNil(o.DataRx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataRx
}

// GetDataRxOk returns a tuple with the DataRx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3StatisticGetNetworkResponse) GetDataRxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || isNil(o.DataRx) {
    return nil, false
	}
	return o.DataRx, true
}

// HasDataRx returns a boolean if a field has been set.
func (o *S3StatisticGetNetworkResponse) HasDataRx() bool {
	if o != nil && !isNil(o.DataRx) {
		return true
	}

	return false
}

// SetDataRx gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataRx field.
func (o *S3StatisticGetNetworkResponse) SetDataRx(v StructuresStatisticSeriesData) {
	o.DataRx = &v
}

// GetDataTx returns the DataTx field value if set, zero value otherwise.
func (o *S3StatisticGetNetworkResponse) GetDataTx() StructuresStatisticSeriesData {
	if o == nil || isNil(o.DataTx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataTx
}

// GetDataTxOk returns a tuple with the DataTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3StatisticGetNetworkResponse) GetDataTxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || isNil(o.DataTx) {
    return nil, false
	}
	return o.DataTx, true
}

// HasDataTx returns a boolean if a field has been set.
func (o *S3StatisticGetNetworkResponse) HasDataTx() bool {
	if o != nil && !isNil(o.DataTx) {
		return true
	}

	return false
}

// SetDataTx gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataTx field.
func (o *S3StatisticGetNetworkResponse) SetDataTx(v StructuresStatisticSeriesData) {
	o.DataTx = &v
}

func (o S3StatisticGetNetworkResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.DataRx) {
		toSerialize["data_rx"] = o.DataRx
	}
	if !isNil(o.DataTx) {
		toSerialize["data_tx"] = o.DataTx
	}
	return json.Marshal(toSerialize)
}

type NullableS3StatisticGetNetworkResponse struct {
	value *S3StatisticGetNetworkResponse
	isSet bool
}

func (v NullableS3StatisticGetNetworkResponse) Get() *S3StatisticGetNetworkResponse {
	return v.value
}

func (v *NullableS3StatisticGetNetworkResponse) Set(val *S3StatisticGetNetworkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableS3StatisticGetNetworkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableS3StatisticGetNetworkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3StatisticGetNetworkResponse(val *S3StatisticGetNetworkResponse) *NullableS3StatisticGetNetworkResponse {
	return &NullableS3StatisticGetNetworkResponse{value: val, isSet: true}
}

func (v NullableS3StatisticGetNetworkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3StatisticGetNetworkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


