/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnStatisticGetRequestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnStatisticGetRequestResponse{}

// CdnStatisticGetRequestResponse struct for CdnStatisticGetRequestResponse
type CdnStatisticGetRequestResponse struct {
	Code2xx *StructuresStatisticSeriesData `json:"code_2xx,omitempty"`
	Code3xx *StructuresStatisticSeriesData `json:"code_3xx,omitempty"`
	Code4xx *StructuresStatisticSeriesData `json:"code_4xx,omitempty"`
	Code5xx *StructuresStatisticSeriesData `json:"code_5xx,omitempty"`
}

// NewCdnStatisticGetRequestResponse instantiates a new CdnStatisticGetRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnStatisticGetRequestResponse() *CdnStatisticGetRequestResponse {
	this := CdnStatisticGetRequestResponse{}
	return &this
}

// NewCdnStatisticGetRequestResponseWithDefaults instantiates a new CdnStatisticGetRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnStatisticGetRequestResponseWithDefaults() *CdnStatisticGetRequestResponse {
	this := CdnStatisticGetRequestResponse{}
	return &this
}

// GetCode2xx returns the Code2xx field value if set, zero value otherwise.
func (o *CdnStatisticGetRequestResponse) GetCode2xx() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.Code2xx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.Code2xx
}

// GetCode2xxOk returns a tuple with the Code2xx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnStatisticGetRequestResponse) GetCode2xxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.Code2xx) {
		return nil, false
	}
	return o.Code2xx, true
}

// HasCode2xx returns a boolean if a field has been set.
func (o *CdnStatisticGetRequestResponse) HasCode2xx() bool {
	if o != nil && !IsNil(o.Code2xx) {
		return true
	}

	return false
}

// SetCode2xx gets a reference to the given StructuresStatisticSeriesData and assigns it to the Code2xx field.
func (o *CdnStatisticGetRequestResponse) SetCode2xx(v StructuresStatisticSeriesData) {
	o.Code2xx = &v
}

// GetCode3xx returns the Code3xx field value if set, zero value otherwise.
func (o *CdnStatisticGetRequestResponse) GetCode3xx() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.Code3xx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.Code3xx
}

// GetCode3xxOk returns a tuple with the Code3xx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnStatisticGetRequestResponse) GetCode3xxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.Code3xx) {
		return nil, false
	}
	return o.Code3xx, true
}

// HasCode3xx returns a boolean if a field has been set.
func (o *CdnStatisticGetRequestResponse) HasCode3xx() bool {
	if o != nil && !IsNil(o.Code3xx) {
		return true
	}

	return false
}

// SetCode3xx gets a reference to the given StructuresStatisticSeriesData and assigns it to the Code3xx field.
func (o *CdnStatisticGetRequestResponse) SetCode3xx(v StructuresStatisticSeriesData) {
	o.Code3xx = &v
}

// GetCode4xx returns the Code4xx field value if set, zero value otherwise.
func (o *CdnStatisticGetRequestResponse) GetCode4xx() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.Code4xx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.Code4xx
}

// GetCode4xxOk returns a tuple with the Code4xx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnStatisticGetRequestResponse) GetCode4xxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.Code4xx) {
		return nil, false
	}
	return o.Code4xx, true
}

// HasCode4xx returns a boolean if a field has been set.
func (o *CdnStatisticGetRequestResponse) HasCode4xx() bool {
	if o != nil && !IsNil(o.Code4xx) {
		return true
	}

	return false
}

// SetCode4xx gets a reference to the given StructuresStatisticSeriesData and assigns it to the Code4xx field.
func (o *CdnStatisticGetRequestResponse) SetCode4xx(v StructuresStatisticSeriesData) {
	o.Code4xx = &v
}

// GetCode5xx returns the Code5xx field value if set, zero value otherwise.
func (o *CdnStatisticGetRequestResponse) GetCode5xx() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.Code5xx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.Code5xx
}

// GetCode5xxOk returns a tuple with the Code5xx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnStatisticGetRequestResponse) GetCode5xxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.Code5xx) {
		return nil, false
	}
	return o.Code5xx, true
}

// HasCode5xx returns a boolean if a field has been set.
func (o *CdnStatisticGetRequestResponse) HasCode5xx() bool {
	if o != nil && !IsNil(o.Code5xx) {
		return true
	}

	return false
}

// SetCode5xx gets a reference to the given StructuresStatisticSeriesData and assigns it to the Code5xx field.
func (o *CdnStatisticGetRequestResponse) SetCode5xx(v StructuresStatisticSeriesData) {
	o.Code5xx = &v
}

func (o CdnStatisticGetRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnStatisticGetRequestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code2xx) {
		toSerialize["code_2xx"] = o.Code2xx
	}
	if !IsNil(o.Code3xx) {
		toSerialize["code_3xx"] = o.Code3xx
	}
	if !IsNil(o.Code4xx) {
		toSerialize["code_4xx"] = o.Code4xx
	}
	if !IsNil(o.Code5xx) {
		toSerialize["code_5xx"] = o.Code5xx
	}
	return toSerialize, nil
}

type NullableCdnStatisticGetRequestResponse struct {
	value *CdnStatisticGetRequestResponse
	isSet bool
}

func (v NullableCdnStatisticGetRequestResponse) Get() *CdnStatisticGetRequestResponse {
	return v.value
}

func (v *NullableCdnStatisticGetRequestResponse) Set(val *CdnStatisticGetRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnStatisticGetRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnStatisticGetRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnStatisticGetRequestResponse(val *CdnStatisticGetRequestResponse) *NullableCdnStatisticGetRequestResponse {
	return &NullableCdnStatisticGetRequestResponse{value: val, isSet: true}
}

func (v NullableCdnStatisticGetRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnStatisticGetRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


