/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnStatisticGetTrafficResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnStatisticGetTrafficResponse{}

// CdnStatisticGetTrafficResponse struct for CdnStatisticGetTrafficResponse
type CdnStatisticGetTrafficResponse struct {
	DataTx *StructuresStatisticSeriesData `json:"data_tx,omitempty"`
}

// NewCdnStatisticGetTrafficResponse instantiates a new CdnStatisticGetTrafficResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnStatisticGetTrafficResponse() *CdnStatisticGetTrafficResponse {
	this := CdnStatisticGetTrafficResponse{}
	return &this
}

// NewCdnStatisticGetTrafficResponseWithDefaults instantiates a new CdnStatisticGetTrafficResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnStatisticGetTrafficResponseWithDefaults() *CdnStatisticGetTrafficResponse {
	this := CdnStatisticGetTrafficResponse{}
	return &this
}

// GetDataTx returns the DataTx field value if set, zero value otherwise.
func (o *CdnStatisticGetTrafficResponse) GetDataTx() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.DataTx) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DataTx
}

// GetDataTxOk returns a tuple with the DataTx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnStatisticGetTrafficResponse) GetDataTxOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.DataTx) {
		return nil, false
	}
	return o.DataTx, true
}

// HasDataTx returns a boolean if a field has been set.
func (o *CdnStatisticGetTrafficResponse) HasDataTx() bool {
	if o != nil && !IsNil(o.DataTx) {
		return true
	}

	return false
}

// SetDataTx gets a reference to the given StructuresStatisticSeriesData and assigns it to the DataTx field.
func (o *CdnStatisticGetTrafficResponse) SetDataTx(v StructuresStatisticSeriesData) {
	o.DataTx = &v
}

func (o CdnStatisticGetTrafficResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnStatisticGetTrafficResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataTx) {
		toSerialize["data_tx"] = o.DataTx
	}
	return toSerialize, nil
}

type NullableCdnStatisticGetTrafficResponse struct {
	value *CdnStatisticGetTrafficResponse
	isSet bool
}

func (v NullableCdnStatisticGetTrafficResponse) Get() *CdnStatisticGetTrafficResponse {
	return v.value
}

func (v *NullableCdnStatisticGetTrafficResponse) Set(val *CdnStatisticGetTrafficResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnStatisticGetTrafficResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnStatisticGetTrafficResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnStatisticGetTrafficResponse(val *CdnStatisticGetTrafficResponse) *NullableCdnStatisticGetTrafficResponse {
	return &NullableCdnStatisticGetTrafficResponse{value: val, isSet: true}
}

func (v NullableCdnStatisticGetTrafficResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnStatisticGetTrafficResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


