/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// ProjectUpdateProjectResponse struct for ProjectUpdateProjectResponse
type ProjectUpdateProjectResponse struct {
	Project *ProjectProject `json:"project,omitempty"`
	Error *ProjectUpdateProjectResponseError `json:"error,omitempty"`
}

// NewProjectUpdateProjectResponse instantiates a new ProjectUpdateProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectUpdateProjectResponse() *ProjectUpdateProjectResponse {
	this := ProjectUpdateProjectResponse{}
	return &this
}

// NewProjectUpdateProjectResponseWithDefaults instantiates a new ProjectUpdateProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectUpdateProjectResponseWithDefaults() *ProjectUpdateProjectResponse {
	this := ProjectUpdateProjectResponse{}
	return &this
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ProjectUpdateProjectResponse) GetProject() ProjectProject {
	if o == nil || isNil(o.Project) {
		var ret ProjectProject
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdateProjectResponse) GetProjectOk() (*ProjectProject, bool) {
	if o == nil || isNil(o.Project) {
    return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ProjectUpdateProjectResponse) HasProject() bool {
	if o != nil && !isNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given ProjectProject and assigns it to the Project field.
func (o *ProjectUpdateProjectResponse) SetProject(v ProjectProject) {
	o.Project = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ProjectUpdateProjectResponse) GetError() ProjectUpdateProjectResponseError {
	if o == nil || isNil(o.Error) {
		var ret ProjectUpdateProjectResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectUpdateProjectResponse) GetErrorOk() (*ProjectUpdateProjectResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ProjectUpdateProjectResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ProjectUpdateProjectResponseError and assigns it to the Error field.
func (o *ProjectUpdateProjectResponse) SetError(v ProjectUpdateProjectResponseError) {
	o.Error = &v
}

func (o ProjectUpdateProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableProjectUpdateProjectResponse struct {
	value *ProjectUpdateProjectResponse
	isSet bool
}

func (v NullableProjectUpdateProjectResponse) Get() *ProjectUpdateProjectResponse {
	return v.value
}

func (v *NullableProjectUpdateProjectResponse) Set(val *ProjectUpdateProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectUpdateProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectUpdateProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectUpdateProjectResponse(val *ProjectUpdateProjectResponse) *NullableProjectUpdateProjectResponse {
	return &NullableProjectUpdateProjectResponse{value: val, isSet: true}
}

func (v NullableProjectUpdateProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectUpdateProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


