/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnChangeResourceDomainsResponseDomainError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnChangeResourceDomainsResponseDomainError{}

// CdnChangeResourceDomainsResponseDomainError struct for CdnChangeResourceDomainsResponseDomainError
type CdnChangeResourceDomainsResponseDomainError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Domain *string `json:"domain,omitempty"`
	DomainAlreadyUsedDetails *CdnChangeResourceDomainsResponseDomainErrorDomainAlreadyUsedDetails `json:"domain_already_used_details,omitempty"`
}

// NewCdnChangeResourceDomainsResponseDomainError instantiates a new CdnChangeResourceDomainsResponseDomainError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnChangeResourceDomainsResponseDomainError() *CdnChangeResourceDomainsResponseDomainError {
	this := CdnChangeResourceDomainsResponseDomainError{}
	return &this
}

// NewCdnChangeResourceDomainsResponseDomainErrorWithDefaults instantiates a new CdnChangeResourceDomainsResponseDomainError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnChangeResourceDomainsResponseDomainErrorWithDefaults() *CdnChangeResourceDomainsResponseDomainError {
	this := CdnChangeResourceDomainsResponseDomainError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CdnChangeResourceDomainsResponseDomainError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CdnChangeResourceDomainsResponseDomainError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CdnChangeResourceDomainsResponseDomainError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CdnChangeResourceDomainsResponseDomainError) SetMessage(v string) {
	o.Message = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *CdnChangeResourceDomainsResponseDomainError) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *CdnChangeResourceDomainsResponseDomainError) SetDomain(v string) {
	o.Domain = &v
}

// GetDomainAlreadyUsedDetails returns the DomainAlreadyUsedDetails field value if set, zero value otherwise.
func (o *CdnChangeResourceDomainsResponseDomainError) GetDomainAlreadyUsedDetails() CdnChangeResourceDomainsResponseDomainErrorDomainAlreadyUsedDetails {
	if o == nil || IsNil(o.DomainAlreadyUsedDetails) {
		var ret CdnChangeResourceDomainsResponseDomainErrorDomainAlreadyUsedDetails
		return ret
	}
	return *o.DomainAlreadyUsedDetails
}

// GetDomainAlreadyUsedDetailsOk returns a tuple with the DomainAlreadyUsedDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) GetDomainAlreadyUsedDetailsOk() (*CdnChangeResourceDomainsResponseDomainErrorDomainAlreadyUsedDetails, bool) {
	if o == nil || IsNil(o.DomainAlreadyUsedDetails) {
		return nil, false
	}
	return o.DomainAlreadyUsedDetails, true
}

// HasDomainAlreadyUsedDetails returns a boolean if a field has been set.
func (o *CdnChangeResourceDomainsResponseDomainError) HasDomainAlreadyUsedDetails() bool {
	if o != nil && !IsNil(o.DomainAlreadyUsedDetails) {
		return true
	}

	return false
}

// SetDomainAlreadyUsedDetails gets a reference to the given CdnChangeResourceDomainsResponseDomainErrorDomainAlreadyUsedDetails and assigns it to the DomainAlreadyUsedDetails field.
func (o *CdnChangeResourceDomainsResponseDomainError) SetDomainAlreadyUsedDetails(v CdnChangeResourceDomainsResponseDomainErrorDomainAlreadyUsedDetails) {
	o.DomainAlreadyUsedDetails = &v
}

func (o CdnChangeResourceDomainsResponseDomainError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnChangeResourceDomainsResponseDomainError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.DomainAlreadyUsedDetails) {
		toSerialize["domain_already_used_details"] = o.DomainAlreadyUsedDetails
	}
	return toSerialize, nil
}

type NullableCdnChangeResourceDomainsResponseDomainError struct {
	value *CdnChangeResourceDomainsResponseDomainError
	isSet bool
}

func (v NullableCdnChangeResourceDomainsResponseDomainError) Get() *CdnChangeResourceDomainsResponseDomainError {
	return v.value
}

func (v *NullableCdnChangeResourceDomainsResponseDomainError) Set(val *CdnChangeResourceDomainsResponseDomainError) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnChangeResourceDomainsResponseDomainError) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnChangeResourceDomainsResponseDomainError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnChangeResourceDomainsResponseDomainError(val *CdnChangeResourceDomainsResponseDomainError) *NullableCdnChangeResourceDomainsResponseDomainError {
	return &NullableCdnChangeResourceDomainsResponseDomainError{value: val, isSet: true}
}

func (v NullableCdnChangeResourceDomainsResponseDomainError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnChangeResourceDomainsResponseDomainError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


