/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// S3Ftp struct for S3Ftp
type S3Ftp struct {
	Host *string `json:"host,omitempty"`
	Port *int32 `json:"port,omitempty"`
	Login *string `json:"login,omitempty"`
	Password *string `json:"password,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewS3Ftp instantiates a new S3Ftp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3Ftp() *S3Ftp {
	this := S3Ftp{}
	return &this
}

// NewS3FtpWithDefaults instantiates a new S3Ftp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3FtpWithDefaults() *S3Ftp {
	this := S3Ftp{}
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *S3Ftp) GetHost() string {
	if o == nil || isNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Ftp) GetHostOk() (*string, bool) {
	if o == nil || isNil(o.Host) {
    return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *S3Ftp) HasHost() bool {
	if o != nil && !isNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *S3Ftp) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *S3Ftp) GetPort() int32 {
	if o == nil || isNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Ftp) GetPortOk() (*int32, bool) {
	if o == nil || isNil(o.Port) {
    return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *S3Ftp) HasPort() bool {
	if o != nil && !isNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *S3Ftp) SetPort(v int32) {
	o.Port = &v
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *S3Ftp) GetLogin() string {
	if o == nil || isNil(o.Login) {
		var ret string
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Ftp) GetLoginOk() (*string, bool) {
	if o == nil || isNil(o.Login) {
    return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *S3Ftp) HasLogin() bool {
	if o != nil && !isNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given string and assigns it to the Login field.
func (o *S3Ftp) SetLogin(v string) {
	o.Login = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *S3Ftp) GetPassword() string {
	if o == nil || isNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Ftp) GetPasswordOk() (*string, bool) {
	if o == nil || isNil(o.Password) {
    return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *S3Ftp) HasPassword() bool {
	if o != nil && !isNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *S3Ftp) SetPassword(v string) {
	o.Password = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *S3Ftp) GetStatus() string {
	if o == nil || isNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3Ftp) GetStatusOk() (*string, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *S3Ftp) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *S3Ftp) SetStatus(v string) {
	o.Status = &v
}

func (o S3Ftp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !isNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !isNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	if !isNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableS3Ftp struct {
	value *S3Ftp
	isSet bool
}

func (v NullableS3Ftp) Get() *S3Ftp {
	return v.value
}

func (v *NullableS3Ftp) Set(val *S3Ftp) {
	v.value = val
	v.isSet = true
}

func (v NullableS3Ftp) IsSet() bool {
	return v.isSet
}

func (v *NullableS3Ftp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3Ftp(val *S3Ftp) *NullableS3Ftp {
	return &NullableS3Ftp{value: val, isSet: true}
}

func (v NullableS3Ftp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3Ftp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


