/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnPurgeAllCacheResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnPurgeAllCacheResponse{}

// CdnPurgeAllCacheResponse struct for CdnPurgeAllCacheResponse
type CdnPurgeAllCacheResponse struct {
	Cdn *CdnCdn `json:"cdn,omitempty"`
	Error *CdnPurgeAllCacheResponseError `json:"error,omitempty"`
}

// NewCdnPurgeAllCacheResponse instantiates a new CdnPurgeAllCacheResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnPurgeAllCacheResponse() *CdnPurgeAllCacheResponse {
	this := CdnPurgeAllCacheResponse{}
	return &this
}

// NewCdnPurgeAllCacheResponseWithDefaults instantiates a new CdnPurgeAllCacheResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnPurgeAllCacheResponseWithDefaults() *CdnPurgeAllCacheResponse {
	this := CdnPurgeAllCacheResponse{}
	return &this
}

// GetCdn returns the Cdn field value if set, zero value otherwise.
func (o *CdnPurgeAllCacheResponse) GetCdn() CdnCdn {
	if o == nil || IsNil(o.Cdn) {
		var ret CdnCdn
		return ret
	}
	return *o.Cdn
}

// GetCdnOk returns a tuple with the Cdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnPurgeAllCacheResponse) GetCdnOk() (*CdnCdn, bool) {
	if o == nil || IsNil(o.Cdn) {
		return nil, false
	}
	return o.Cdn, true
}

// HasCdn returns a boolean if a field has been set.
func (o *CdnPurgeAllCacheResponse) HasCdn() bool {
	if o != nil && !IsNil(o.Cdn) {
		return true
	}

	return false
}

// SetCdn gets a reference to the given CdnCdn and assigns it to the Cdn field.
func (o *CdnPurgeAllCacheResponse) SetCdn(v CdnCdn) {
	o.Cdn = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CdnPurgeAllCacheResponse) GetError() CdnPurgeAllCacheResponseError {
	if o == nil || IsNil(o.Error) {
		var ret CdnPurgeAllCacheResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnPurgeAllCacheResponse) GetErrorOk() (*CdnPurgeAllCacheResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CdnPurgeAllCacheResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CdnPurgeAllCacheResponseError and assigns it to the Error field.
func (o *CdnPurgeAllCacheResponse) SetError(v CdnPurgeAllCacheResponseError) {
	o.Error = &v
}

func (o CdnPurgeAllCacheResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnPurgeAllCacheResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cdn) {
		toSerialize["cdn"] = o.Cdn
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableCdnPurgeAllCacheResponse struct {
	value *CdnPurgeAllCacheResponse
	isSet bool
}

func (v NullableCdnPurgeAllCacheResponse) Get() *CdnPurgeAllCacheResponse {
	return v.value
}

func (v *NullableCdnPurgeAllCacheResponse) Set(val *CdnPurgeAllCacheResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnPurgeAllCacheResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnPurgeAllCacheResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnPurgeAllCacheResponse(val *CdnPurgeAllCacheResponse) *NullableCdnPurgeAllCacheResponse {
	return &NullableCdnPurgeAllCacheResponse{value: val, isSet: true}
}

func (v NullableCdnPurgeAllCacheResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnPurgeAllCacheResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


