/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the ProjectRemoveProjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectRemoveProjectResponse{}

// ProjectRemoveProjectResponse struct for ProjectRemoveProjectResponse
type ProjectRemoveProjectResponse struct {
	Success map[string]interface{} `json:"success,omitempty"`
	Error *ProjectRemoveProjectResponseError `json:"error,omitempty"`
}

// NewProjectRemoveProjectResponse instantiates a new ProjectRemoveProjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectRemoveProjectResponse() *ProjectRemoveProjectResponse {
	this := ProjectRemoveProjectResponse{}
	return &this
}

// NewProjectRemoveProjectResponseWithDefaults instantiates a new ProjectRemoveProjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectRemoveProjectResponseWithDefaults() *ProjectRemoveProjectResponse {
	this := ProjectRemoveProjectResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ProjectRemoveProjectResponse) GetSuccess() map[string]interface{} {
	if o == nil || IsNil(o.Success) {
		var ret map[string]interface{}
		return ret
	}
	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectRemoveProjectResponse) GetSuccessOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Success) {
		return map[string]interface{}{}, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ProjectRemoveProjectResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given map[string]interface{} and assigns it to the Success field.
func (o *ProjectRemoveProjectResponse) SetSuccess(v map[string]interface{}) {
	o.Success = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ProjectRemoveProjectResponse) GetError() ProjectRemoveProjectResponseError {
	if o == nil || IsNil(o.Error) {
		var ret ProjectRemoveProjectResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectRemoveProjectResponse) GetErrorOk() (*ProjectRemoveProjectResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ProjectRemoveProjectResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ProjectRemoveProjectResponseError and assigns it to the Error field.
func (o *ProjectRemoveProjectResponse) SetError(v ProjectRemoveProjectResponseError) {
	o.Error = &v
}

func (o ProjectRemoveProjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectRemoveProjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableProjectRemoveProjectResponse struct {
	value *ProjectRemoveProjectResponse
	isSet bool
}

func (v NullableProjectRemoveProjectResponse) Get() *ProjectRemoveProjectResponse {
	return v.value
}

func (v *NullableProjectRemoveProjectResponse) Set(val *ProjectRemoveProjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectRemoveProjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectRemoveProjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectRemoveProjectResponse(val *ProjectRemoveProjectResponse) *NullableProjectRemoveProjectResponse {
	return &NullableProjectRemoveProjectResponse{value: val, isSet: true}
}

func (v NullableProjectRemoveProjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectRemoveProjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


