/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnCdnCreateParamsSourceParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnCdnCreateParamsSourceParams{}

// CdnCdnCreateParamsSourceParams struct for CdnCdnCreateParamsSourceParams
type CdnCdnCreateParamsSourceParams struct {
	CdnServiceId *string `json:"cdn_service_id,omitempty"`
	SourceServiceId *string `json:"source_service_id,omitempty"`
	SourceServiceType *string `json:"source_service_type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	SourceProtocol *string `json:"source_protocol,omitempty"`
}

// NewCdnCdnCreateParamsSourceParams instantiates a new CdnCdnCreateParamsSourceParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnCdnCreateParamsSourceParams() *CdnCdnCreateParamsSourceParams {
	this := CdnCdnCreateParamsSourceParams{}
	return &this
}

// NewCdnCdnCreateParamsSourceParamsWithDefaults instantiates a new CdnCdnCreateParamsSourceParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnCdnCreateParamsSourceParamsWithDefaults() *CdnCdnCreateParamsSourceParams {
	this := CdnCdnCreateParamsSourceParams{}
	return &this
}

// GetCdnServiceId returns the CdnServiceId field value if set, zero value otherwise.
func (o *CdnCdnCreateParamsSourceParams) GetCdnServiceId() string {
	if o == nil || IsNil(o.CdnServiceId) {
		var ret string
		return ret
	}
	return *o.CdnServiceId
}

// GetCdnServiceIdOk returns a tuple with the CdnServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCdnCreateParamsSourceParams) GetCdnServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.CdnServiceId) {
		return nil, false
	}
	return o.CdnServiceId, true
}

// HasCdnServiceId returns a boolean if a field has been set.
func (o *CdnCdnCreateParamsSourceParams) HasCdnServiceId() bool {
	if o != nil && !IsNil(o.CdnServiceId) {
		return true
	}

	return false
}

// SetCdnServiceId gets a reference to the given string and assigns it to the CdnServiceId field.
func (o *CdnCdnCreateParamsSourceParams) SetCdnServiceId(v string) {
	o.CdnServiceId = &v
}

// GetSourceServiceId returns the SourceServiceId field value if set, zero value otherwise.
func (o *CdnCdnCreateParamsSourceParams) GetSourceServiceId() string {
	if o == nil || IsNil(o.SourceServiceId) {
		var ret string
		return ret
	}
	return *o.SourceServiceId
}

// GetSourceServiceIdOk returns a tuple with the SourceServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCdnCreateParamsSourceParams) GetSourceServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceServiceId) {
		return nil, false
	}
	return o.SourceServiceId, true
}

// HasSourceServiceId returns a boolean if a field has been set.
func (o *CdnCdnCreateParamsSourceParams) HasSourceServiceId() bool {
	if o != nil && !IsNil(o.SourceServiceId) {
		return true
	}

	return false
}

// SetSourceServiceId gets a reference to the given string and assigns it to the SourceServiceId field.
func (o *CdnCdnCreateParamsSourceParams) SetSourceServiceId(v string) {
	o.SourceServiceId = &v
}

// GetSourceServiceType returns the SourceServiceType field value if set, zero value otherwise.
func (o *CdnCdnCreateParamsSourceParams) GetSourceServiceType() string {
	if o == nil || IsNil(o.SourceServiceType) {
		var ret string
		return ret
	}
	return *o.SourceServiceType
}

// GetSourceServiceTypeOk returns a tuple with the SourceServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCdnCreateParamsSourceParams) GetSourceServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceServiceType) {
		return nil, false
	}
	return o.SourceServiceType, true
}

// HasSourceServiceType returns a boolean if a field has been set.
func (o *CdnCdnCreateParamsSourceParams) HasSourceServiceType() bool {
	if o != nil && !IsNil(o.SourceServiceType) {
		return true
	}

	return false
}

// SetSourceServiceType gets a reference to the given string and assigns it to the SourceServiceType field.
func (o *CdnCdnCreateParamsSourceParams) SetSourceServiceType(v string) {
	o.SourceServiceType = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *CdnCdnCreateParamsSourceParams) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCdnCreateParamsSourceParams) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *CdnCdnCreateParamsSourceParams) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *CdnCdnCreateParamsSourceParams) SetDomain(v string) {
	o.Domain = &v
}

// GetSourceProtocol returns the SourceProtocol field value if set, zero value otherwise.
func (o *CdnCdnCreateParamsSourceParams) GetSourceProtocol() string {
	if o == nil || IsNil(o.SourceProtocol) {
		var ret string
		return ret
	}
	return *o.SourceProtocol
}

// GetSourceProtocolOk returns a tuple with the SourceProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCdnCreateParamsSourceParams) GetSourceProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.SourceProtocol) {
		return nil, false
	}
	return o.SourceProtocol, true
}

// HasSourceProtocol returns a boolean if a field has been set.
func (o *CdnCdnCreateParamsSourceParams) HasSourceProtocol() bool {
	if o != nil && !IsNil(o.SourceProtocol) {
		return true
	}

	return false
}

// SetSourceProtocol gets a reference to the given string and assigns it to the SourceProtocol field.
func (o *CdnCdnCreateParamsSourceParams) SetSourceProtocol(v string) {
	o.SourceProtocol = &v
}

func (o CdnCdnCreateParamsSourceParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnCdnCreateParamsSourceParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CdnServiceId) {
		toSerialize["cdn_service_id"] = o.CdnServiceId
	}
	if !IsNil(o.SourceServiceId) {
		toSerialize["source_service_id"] = o.SourceServiceId
	}
	if !IsNil(o.SourceServiceType) {
		toSerialize["source_service_type"] = o.SourceServiceType
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.SourceProtocol) {
		toSerialize["source_protocol"] = o.SourceProtocol
	}
	return toSerialize, nil
}

type NullableCdnCdnCreateParamsSourceParams struct {
	value *CdnCdnCreateParamsSourceParams
	isSet bool
}

func (v NullableCdnCdnCreateParamsSourceParams) Get() *CdnCdnCreateParamsSourceParams {
	return v.value
}

func (v *NullableCdnCdnCreateParamsSourceParams) Set(val *CdnCdnCreateParamsSourceParams) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnCdnCreateParamsSourceParams) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnCdnCreateParamsSourceParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnCdnCreateParamsSourceParams(val *CdnCdnCreateParamsSourceParams) *NullableCdnCdnCreateParamsSourceParams {
	return &NullableCdnCdnCreateParamsSourceParams{value: val, isSet: true}
}

func (v NullableCdnCdnCreateParamsSourceParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnCdnCreateParamsSourceParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


