/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the S3ChangePublicRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3ChangePublicRequest{}

// S3ChangePublicRequest struct for S3ChangePublicRequest
type S3ChangePublicRequest struct {
	ServiceId *string `json:"service_id,omitempty"`
	Public *bool `json:"public,omitempty"`
}

// NewS3ChangePublicRequest instantiates a new S3ChangePublicRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3ChangePublicRequest() *S3ChangePublicRequest {
	this := S3ChangePublicRequest{}
	return &this
}

// NewS3ChangePublicRequestWithDefaults instantiates a new S3ChangePublicRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3ChangePublicRequestWithDefaults() *S3ChangePublicRequest {
	this := S3ChangePublicRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *S3ChangePublicRequest) GetServiceId() string {
	if o == nil || IsNil(o.ServiceId) {
		var ret string
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ChangePublicRequest) GetServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *S3ChangePublicRequest) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given string and assigns it to the ServiceId field.
func (o *S3ChangePublicRequest) SetServiceId(v string) {
	o.ServiceId = &v
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *S3ChangePublicRequest) GetPublic() bool {
	if o == nil || IsNil(o.Public) {
		var ret bool
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ChangePublicRequest) GetPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *S3ChangePublicRequest) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given bool and assigns it to the Public field.
func (o *S3ChangePublicRequest) SetPublic(v bool) {
	o.Public = &v
}

func (o S3ChangePublicRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3ChangePublicRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	return toSerialize, nil
}

type NullableS3ChangePublicRequest struct {
	value *S3ChangePublicRequest
	isSet bool
}

func (v NullableS3ChangePublicRequest) Get() *S3ChangePublicRequest {
	return v.value
}

func (v *NullableS3ChangePublicRequest) Set(val *S3ChangePublicRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableS3ChangePublicRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableS3ChangePublicRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3ChangePublicRequest(val *S3ChangePublicRequest) *NullableS3ChangePublicRequest {
	return &NullableS3ChangePublicRequest{value: val, isSet: true}
}

func (v NullableS3ChangePublicRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3ChangePublicRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


