/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnSettingsGeoAcl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnSettingsGeoAcl{}

// CdnSettingsGeoAcl struct for CdnSettingsGeoAcl
type CdnSettingsGeoAcl struct {
	Enable *bool `json:"enable,omitempty"`
	PolicyType *string `json:"policy_type,omitempty"`
	ExceptedValues *map[string]CdnSettingsGeoAclStringArray `json:"excepted_values,omitempty"`
}

// NewCdnSettingsGeoAcl instantiates a new CdnSettingsGeoAcl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsGeoAcl() *CdnSettingsGeoAcl {
	this := CdnSettingsGeoAcl{}
	return &this
}

// NewCdnSettingsGeoAclWithDefaults instantiates a new CdnSettingsGeoAcl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsGeoAclWithDefaults() *CdnSettingsGeoAcl {
	this := CdnSettingsGeoAcl{}
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *CdnSettingsGeoAcl) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsGeoAcl) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *CdnSettingsGeoAcl) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *CdnSettingsGeoAcl) SetEnable(v bool) {
	o.Enable = &v
}

// GetPolicyType returns the PolicyType field value if set, zero value otherwise.
func (o *CdnSettingsGeoAcl) GetPolicyType() string {
	if o == nil || IsNil(o.PolicyType) {
		var ret string
		return ret
	}
	return *o.PolicyType
}

// GetPolicyTypeOk returns a tuple with the PolicyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsGeoAcl) GetPolicyTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyType) {
		return nil, false
	}
	return o.PolicyType, true
}

// HasPolicyType returns a boolean if a field has been set.
func (o *CdnSettingsGeoAcl) HasPolicyType() bool {
	if o != nil && !IsNil(o.PolicyType) {
		return true
	}

	return false
}

// SetPolicyType gets a reference to the given string and assigns it to the PolicyType field.
func (o *CdnSettingsGeoAcl) SetPolicyType(v string) {
	o.PolicyType = &v
}

// GetExceptedValues returns the ExceptedValues field value if set, zero value otherwise.
func (o *CdnSettingsGeoAcl) GetExceptedValues() map[string]CdnSettingsGeoAclStringArray {
	if o == nil || IsNil(o.ExceptedValues) {
		var ret map[string]CdnSettingsGeoAclStringArray
		return ret
	}
	return *o.ExceptedValues
}

// GetExceptedValuesOk returns a tuple with the ExceptedValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsGeoAcl) GetExceptedValuesOk() (*map[string]CdnSettingsGeoAclStringArray, bool) {
	if o == nil || IsNil(o.ExceptedValues) {
		return nil, false
	}
	return o.ExceptedValues, true
}

// HasExceptedValues returns a boolean if a field has been set.
func (o *CdnSettingsGeoAcl) HasExceptedValues() bool {
	if o != nil && !IsNil(o.ExceptedValues) {
		return true
	}

	return false
}

// SetExceptedValues gets a reference to the given map[string]CdnSettingsGeoAclStringArray and assigns it to the ExceptedValues field.
func (o *CdnSettingsGeoAcl) SetExceptedValues(v map[string]CdnSettingsGeoAclStringArray) {
	o.ExceptedValues = &v
}

func (o CdnSettingsGeoAcl) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnSettingsGeoAcl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.PolicyType) {
		toSerialize["policy_type"] = o.PolicyType
	}
	if !IsNil(o.ExceptedValues) {
		toSerialize["excepted_values"] = o.ExceptedValues
	}
	return toSerialize, nil
}

type NullableCdnSettingsGeoAcl struct {
	value *CdnSettingsGeoAcl
	isSet bool
}

func (v NullableCdnSettingsGeoAcl) Get() *CdnSettingsGeoAcl {
	return v.value
}

func (v *NullableCdnSettingsGeoAcl) Set(val *CdnSettingsGeoAcl) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsGeoAcl) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsGeoAcl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsGeoAcl(val *CdnSettingsGeoAcl) *NullableCdnSettingsGeoAcl {
	return &NullableCdnSettingsGeoAcl{value: val, isSet: true}
}

func (v NullableCdnSettingsGeoAcl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsGeoAcl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


