/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CdnPurgeCacheByPathsResponseError struct for CdnPurgeCacheByPathsResponseError
type CdnPurgeCacheByPathsResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCdnPurgeCacheByPathsResponseError instantiates a new CdnPurgeCacheByPathsResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnPurgeCacheByPathsResponseError() *CdnPurgeCacheByPathsResponseError {
	this := CdnPurgeCacheByPathsResponseError{}
	return &this
}

// NewCdnPurgeCacheByPathsResponseErrorWithDefaults instantiates a new CdnPurgeCacheByPathsResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnPurgeCacheByPathsResponseErrorWithDefaults() *CdnPurgeCacheByPathsResponseError {
	this := CdnPurgeCacheByPathsResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CdnPurgeCacheByPathsResponseError) GetCode() string {
	if o == nil || isNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnPurgeCacheByPathsResponseError) GetCodeOk() (*string, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CdnPurgeCacheByPathsResponseError) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CdnPurgeCacheByPathsResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CdnPurgeCacheByPathsResponseError) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnPurgeCacheByPathsResponseError) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CdnPurgeCacheByPathsResponseError) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CdnPurgeCacheByPathsResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o CdnPurgeCacheByPathsResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableCdnPurgeCacheByPathsResponseError struct {
	value *CdnPurgeCacheByPathsResponseError
	isSet bool
}

func (v NullableCdnPurgeCacheByPathsResponseError) Get() *CdnPurgeCacheByPathsResponseError {
	return v.value
}

func (v *NullableCdnPurgeCacheByPathsResponseError) Set(val *CdnPurgeCacheByPathsResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnPurgeCacheByPathsResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnPurgeCacheByPathsResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnPurgeCacheByPathsResponseError(val *CdnPurgeCacheByPathsResponseError) *NullableCdnPurgeCacheByPathsResponseError {
	return &NullableCdnPurgeCacheByPathsResponseError{value: val, isSet: true}
}

func (v NullableCdnPurgeCacheByPathsResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnPurgeCacheByPathsResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


