/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the NetworkDriveSetMountsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkDriveSetMountsRequest{}

// NetworkDriveSetMountsRequest struct for NetworkDriveSetMountsRequest
type NetworkDriveSetMountsRequest struct {
	ServiceId []string `json:"service_id,omitempty"`
	ResourceId *string `json:"resource_id,omitempty"`
	ResourceType *string `json:"resource_type,omitempty"`
}

// NewNetworkDriveSetMountsRequest instantiates a new NetworkDriveSetMountsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkDriveSetMountsRequest() *NetworkDriveSetMountsRequest {
	this := NetworkDriveSetMountsRequest{}
	return &this
}

// NewNetworkDriveSetMountsRequestWithDefaults instantiates a new NetworkDriveSetMountsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkDriveSetMountsRequestWithDefaults() *NetworkDriveSetMountsRequest {
	this := NetworkDriveSetMountsRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *NetworkDriveSetMountsRequest) GetServiceId() []string {
	if o == nil || IsNil(o.ServiceId) {
		var ret []string
		return ret
	}
	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveSetMountsRequest) GetServiceIdOk() ([]string, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *NetworkDriveSetMountsRequest) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given []string and assigns it to the ServiceId field.
func (o *NetworkDriveSetMountsRequest) SetServiceId(v []string) {
	o.ServiceId = v
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise.
func (o *NetworkDriveSetMountsRequest) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId) {
		var ret string
		return ret
	}
	return *o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveSetMountsRequest) GetResourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceId) {
		return nil, false
	}
	return o.ResourceId, true
}

// HasResourceId returns a boolean if a field has been set.
func (o *NetworkDriveSetMountsRequest) HasResourceId() bool {
	if o != nil && !IsNil(o.ResourceId) {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given string and assigns it to the ResourceId field.
func (o *NetworkDriveSetMountsRequest) SetResourceId(v string) {
	o.ResourceId = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *NetworkDriveSetMountsRequest) GetResourceType() string {
	if o == nil || IsNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveSetMountsRequest) GetResourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *NetworkDriveSetMountsRequest) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *NetworkDriveSetMountsRequest) SetResourceType(v string) {
	o.ResourceType = &v
}

func (o NetworkDriveSetMountsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkDriveSetMountsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !IsNil(o.ResourceId) {
		toSerialize["resource_id"] = o.ResourceId
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resource_type"] = o.ResourceType
	}
	return toSerialize, nil
}

type NullableNetworkDriveSetMountsRequest struct {
	value *NetworkDriveSetMountsRequest
	isSet bool
}

func (v NullableNetworkDriveSetMountsRequest) Get() *NetworkDriveSetMountsRequest {
	return v.value
}

func (v *NullableNetworkDriveSetMountsRequest) Set(val *NetworkDriveSetMountsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkDriveSetMountsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkDriveSetMountsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkDriveSetMountsRequest(val *NetworkDriveSetMountsRequest) *NullableNetworkDriveSetMountsRequest {
	return &NullableNetworkDriveSetMountsRequest{value: val, isSet: true}
}

func (v NullableNetworkDriveSetMountsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkDriveSetMountsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


