/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// ProjectProject struct for ProjectProject
type ProjectProject struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	IsDefault *bool `json:"is_default,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UiPinned *bool `json:"ui_pinned,omitempty"`
	UiPinChangedAt *string `json:"ui_pin_changed_at,omitempty"`
	DisplayRank *string `json:"display_rank,omitempty"`
}

// NewProjectProject instantiates a new ProjectProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectProject() *ProjectProject {
	this := ProjectProject{}
	return &this
}

// NewProjectProjectWithDefaults instantiates a new ProjectProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectProjectWithDefaults() *ProjectProject {
	this := ProjectProject{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectProject) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectProject) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProjectProject) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectProject) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectProject) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectProject) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProjectProject) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectProject) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProjectProject) SetDescription(v string) {
	o.Description = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *ProjectProject) GetIsDefault() bool {
	if o == nil || isNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetIsDefaultOk() (*bool, bool) {
	if o == nil || isNil(o.IsDefault) {
    return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *ProjectProject) HasIsDefault() bool {
	if o != nil && !isNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *ProjectProject) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProjectProject) GetCreatedAt() string {
	if o == nil || isNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetCreatedAtOk() (*string, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProjectProject) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ProjectProject) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectProject) GetUpdatedAt() string {
	if o == nil || isNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetUpdatedAtOk() (*string, bool) {
	if o == nil || isNil(o.UpdatedAt) {
    return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectProject) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ProjectProject) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUiPinned returns the UiPinned field value if set, zero value otherwise.
func (o *ProjectProject) GetUiPinned() bool {
	if o == nil || isNil(o.UiPinned) {
		var ret bool
		return ret
	}
	return *o.UiPinned
}

// GetUiPinnedOk returns a tuple with the UiPinned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetUiPinnedOk() (*bool, bool) {
	if o == nil || isNil(o.UiPinned) {
    return nil, false
	}
	return o.UiPinned, true
}

// HasUiPinned returns a boolean if a field has been set.
func (o *ProjectProject) HasUiPinned() bool {
	if o != nil && !isNil(o.UiPinned) {
		return true
	}

	return false
}

// SetUiPinned gets a reference to the given bool and assigns it to the UiPinned field.
func (o *ProjectProject) SetUiPinned(v bool) {
	o.UiPinned = &v
}

// GetUiPinChangedAt returns the UiPinChangedAt field value if set, zero value otherwise.
func (o *ProjectProject) GetUiPinChangedAt() string {
	if o == nil || isNil(o.UiPinChangedAt) {
		var ret string
		return ret
	}
	return *o.UiPinChangedAt
}

// GetUiPinChangedAtOk returns a tuple with the UiPinChangedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetUiPinChangedAtOk() (*string, bool) {
	if o == nil || isNil(o.UiPinChangedAt) {
    return nil, false
	}
	return o.UiPinChangedAt, true
}

// HasUiPinChangedAt returns a boolean if a field has been set.
func (o *ProjectProject) HasUiPinChangedAt() bool {
	if o != nil && !isNil(o.UiPinChangedAt) {
		return true
	}

	return false
}

// SetUiPinChangedAt gets a reference to the given string and assigns it to the UiPinChangedAt field.
func (o *ProjectProject) SetUiPinChangedAt(v string) {
	o.UiPinChangedAt = &v
}

// GetDisplayRank returns the DisplayRank field value if set, zero value otherwise.
func (o *ProjectProject) GetDisplayRank() string {
	if o == nil || isNil(o.DisplayRank) {
		var ret string
		return ret
	}
	return *o.DisplayRank
}

// GetDisplayRankOk returns a tuple with the DisplayRank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectProject) GetDisplayRankOk() (*string, bool) {
	if o == nil || isNil(o.DisplayRank) {
    return nil, false
	}
	return o.DisplayRank, true
}

// HasDisplayRank returns a boolean if a field has been set.
func (o *ProjectProject) HasDisplayRank() bool {
	if o != nil && !isNil(o.DisplayRank) {
		return true
	}

	return false
}

// SetDisplayRank gets a reference to the given string and assigns it to the DisplayRank field.
func (o *ProjectProject) SetDisplayRank(v string) {
	o.DisplayRank = &v
}

func (o ProjectProject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.IsDefault) {
		toSerialize["is_default"] = o.IsDefault
	}
	if !isNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !isNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !isNil(o.UiPinned) {
		toSerialize["ui_pinned"] = o.UiPinned
	}
	if !isNil(o.UiPinChangedAt) {
		toSerialize["ui_pin_changed_at"] = o.UiPinChangedAt
	}
	if !isNil(o.DisplayRank) {
		toSerialize["display_rank"] = o.DisplayRank
	}
	return json.Marshal(toSerialize)
}

type NullableProjectProject struct {
	value *ProjectProject
	isSet bool
}

func (v NullableProjectProject) Get() *ProjectProject {
	return v.value
}

func (v *NullableProjectProject) Set(val *ProjectProject) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectProject) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectProject(val *ProjectProject) *NullableProjectProject {
	return &NullableProjectProject{value: val, isSet: true}
}

func (v NullableProjectProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


