/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CloudBindProjectResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudBindProjectResponseError{}

// CloudBindProjectResponseError struct for CloudBindProjectResponseError
type CloudBindProjectResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCloudBindProjectResponseError instantiates a new CloudBindProjectResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudBindProjectResponseError() *CloudBindProjectResponseError {
	this := CloudBindProjectResponseError{}
	return &this
}

// NewCloudBindProjectResponseErrorWithDefaults instantiates a new CloudBindProjectResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudBindProjectResponseErrorWithDefaults() *CloudBindProjectResponseError {
	this := CloudBindProjectResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CloudBindProjectResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudBindProjectResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CloudBindProjectResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CloudBindProjectResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CloudBindProjectResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudBindProjectResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CloudBindProjectResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CloudBindProjectResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o CloudBindProjectResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudBindProjectResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCloudBindProjectResponseError struct {
	value *CloudBindProjectResponseError
	isSet bool
}

func (v NullableCloudBindProjectResponseError) Get() *CloudBindProjectResponseError {
	return v.value
}

func (v *NullableCloudBindProjectResponseError) Set(val *CloudBindProjectResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudBindProjectResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudBindProjectResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudBindProjectResponseError(val *CloudBindProjectResponseError) *NullableCloudBindProjectResponseError {
	return &NullableCloudBindProjectResponseError{value: val, isSet: true}
}

func (v NullableCloudBindProjectResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudBindProjectResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


