/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CloudBindProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudBindProjectRequest{}

// CloudBindProjectRequest struct for CloudBindProjectRequest
type CloudBindProjectRequest struct {
	ServiceId *string `json:"service_id,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
}

// NewCloudBindProjectRequest instantiates a new CloudBindProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudBindProjectRequest() *CloudBindProjectRequest {
	this := CloudBindProjectRequest{}
	return &this
}

// NewCloudBindProjectRequestWithDefaults instantiates a new CloudBindProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudBindProjectRequestWithDefaults() *CloudBindProjectRequest {
	this := CloudBindProjectRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *CloudBindProjectRequest) GetServiceId() string {
	if o == nil || IsNil(o.ServiceId) {
		var ret string
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudBindProjectRequest) GetServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *CloudBindProjectRequest) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given string and assigns it to the ServiceId field.
func (o *CloudBindProjectRequest) SetServiceId(v string) {
	o.ServiceId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *CloudBindProjectRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudBindProjectRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *CloudBindProjectRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *CloudBindProjectRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o CloudBindProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudBindProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceId) {
		toSerialize["service_id"] = o.ServiceId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	return toSerialize, nil
}

type NullableCloudBindProjectRequest struct {
	value *CloudBindProjectRequest
	isSet bool
}

func (v NullableCloudBindProjectRequest) Get() *CloudBindProjectRequest {
	return v.value
}

func (v *NullableCloudBindProjectRequest) Set(val *CloudBindProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudBindProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudBindProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudBindProjectRequest(val *CloudBindProjectRequest) *NullableCloudBindProjectRequest {
	return &NullableCloudBindProjectRequest{value: val, isSet: true}
}

func (v NullableCloudBindProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudBindProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


