/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CdnSettingsTokenizedUrlSecureKey struct for CdnSettingsTokenizedUrlSecureKey
type CdnSettingsTokenizedUrlSecureKey struct {
	Enable *bool `json:"enable,omitempty"`
	Key *string `json:"key,omitempty"`
	IncludeIp *bool `json:"include_ip,omitempty"`
}

// NewCdnSettingsTokenizedUrlSecureKey instantiates a new CdnSettingsTokenizedUrlSecureKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsTokenizedUrlSecureKey() *CdnSettingsTokenizedUrlSecureKey {
	this := CdnSettingsTokenizedUrlSecureKey{}
	return &this
}

// NewCdnSettingsTokenizedUrlSecureKeyWithDefaults instantiates a new CdnSettingsTokenizedUrlSecureKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsTokenizedUrlSecureKeyWithDefaults() *CdnSettingsTokenizedUrlSecureKey {
	this := CdnSettingsTokenizedUrlSecureKey{}
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *CdnSettingsTokenizedUrlSecureKey) GetEnable() bool {
	if o == nil || isNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsTokenizedUrlSecureKey) GetEnableOk() (*bool, bool) {
	if o == nil || isNil(o.Enable) {
    return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *CdnSettingsTokenizedUrlSecureKey) HasEnable() bool {
	if o != nil && !isNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *CdnSettingsTokenizedUrlSecureKey) SetEnable(v bool) {
	o.Enable = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CdnSettingsTokenizedUrlSecureKey) GetKey() string {
	if o == nil || isNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsTokenizedUrlSecureKey) GetKeyOk() (*string, bool) {
	if o == nil || isNil(o.Key) {
    return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CdnSettingsTokenizedUrlSecureKey) HasKey() bool {
	if o != nil && !isNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CdnSettingsTokenizedUrlSecureKey) SetKey(v string) {
	o.Key = &v
}

// GetIncludeIp returns the IncludeIp field value if set, zero value otherwise.
func (o *CdnSettingsTokenizedUrlSecureKey) GetIncludeIp() bool {
	if o == nil || isNil(o.IncludeIp) {
		var ret bool
		return ret
	}
	return *o.IncludeIp
}

// GetIncludeIpOk returns a tuple with the IncludeIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsTokenizedUrlSecureKey) GetIncludeIpOk() (*bool, bool) {
	if o == nil || isNil(o.IncludeIp) {
    return nil, false
	}
	return o.IncludeIp, true
}

// HasIncludeIp returns a boolean if a field has been set.
func (o *CdnSettingsTokenizedUrlSecureKey) HasIncludeIp() bool {
	if o != nil && !isNil(o.IncludeIp) {
		return true
	}

	return false
}

// SetIncludeIp gets a reference to the given bool and assigns it to the IncludeIp field.
func (o *CdnSettingsTokenizedUrlSecureKey) SetIncludeIp(v bool) {
	o.IncludeIp = &v
}

func (o CdnSettingsTokenizedUrlSecureKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !isNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !isNil(o.IncludeIp) {
		toSerialize["include_ip"] = o.IncludeIp
	}
	return json.Marshal(toSerialize)
}

type NullableCdnSettingsTokenizedUrlSecureKey struct {
	value *CdnSettingsTokenizedUrlSecureKey
	isSet bool
}

func (v NullableCdnSettingsTokenizedUrlSecureKey) Get() *CdnSettingsTokenizedUrlSecureKey {
	return v.value
}

func (v *NullableCdnSettingsTokenizedUrlSecureKey) Set(val *CdnSettingsTokenizedUrlSecureKey) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsTokenizedUrlSecureKey) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsTokenizedUrlSecureKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsTokenizedUrlSecureKey(val *CdnSettingsTokenizedUrlSecureKey) *NullableCdnSettingsTokenizedUrlSecureKey {
	return &NullableCdnSettingsTokenizedUrlSecureKey{value: val, isSet: true}
}

func (v NullableCdnSettingsTokenizedUrlSecureKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsTokenizedUrlSecureKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


