/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CdnChangeResourceDomainsResponseErrors struct for CdnChangeResourceDomainsResponseErrors
type CdnChangeResourceDomainsResponseErrors struct {
	Error []CdnChangeResourceDomainsResponseError `json:"error,omitempty"`
}

// NewCdnChangeResourceDomainsResponseErrors instantiates a new CdnChangeResourceDomainsResponseErrors object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnChangeResourceDomainsResponseErrors() *CdnChangeResourceDomainsResponseErrors {
	this := CdnChangeResourceDomainsResponseErrors{}
	return &this
}

// NewCdnChangeResourceDomainsResponseErrorsWithDefaults instantiates a new CdnChangeResourceDomainsResponseErrors object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnChangeResourceDomainsResponseErrorsWithDefaults() *CdnChangeResourceDomainsResponseErrors {
	this := CdnChangeResourceDomainsResponseErrors{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CdnChangeResourceDomainsResponseErrors) GetError() []CdnChangeResourceDomainsResponseError {
	if o == nil || isNil(o.Error) {
		var ret []CdnChangeResourceDomainsResponseError
		return ret
	}
	return o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnChangeResourceDomainsResponseErrors) GetErrorOk() ([]CdnChangeResourceDomainsResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CdnChangeResourceDomainsResponseErrors) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given []CdnChangeResourceDomainsResponseError and assigns it to the Error field.
func (o *CdnChangeResourceDomainsResponseErrors) SetError(v []CdnChangeResourceDomainsResponseError) {
	o.Error = v
}

func (o CdnChangeResourceDomainsResponseErrors) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableCdnChangeResourceDomainsResponseErrors struct {
	value *CdnChangeResourceDomainsResponseErrors
	isSet bool
}

func (v NullableCdnChangeResourceDomainsResponseErrors) Get() *CdnChangeResourceDomainsResponseErrors {
	return v.value
}

func (v *NullableCdnChangeResourceDomainsResponseErrors) Set(val *CdnChangeResourceDomainsResponseErrors) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnChangeResourceDomainsResponseErrors) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnChangeResourceDomainsResponseErrors) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnChangeResourceDomainsResponseErrors(val *CdnChangeResourceDomainsResponseErrors) *NullableCdnChangeResourceDomainsResponseErrors {
	return &NullableCdnChangeResourceDomainsResponseErrors{value: val, isSet: true}
}

func (v NullableCdnChangeResourceDomainsResponseErrors) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnChangeResourceDomainsResponseErrors) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


