/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// ProjectChangePinnedResponse struct for ProjectChangePinnedResponse
type ProjectChangePinnedResponse struct {
	Project *ProjectProject `json:"project,omitempty"`
	Error *ProjectChangePinnedResponseError `json:"error,omitempty"`
}

// NewProjectChangePinnedResponse instantiates a new ProjectChangePinnedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectChangePinnedResponse() *ProjectChangePinnedResponse {
	this := ProjectChangePinnedResponse{}
	return &this
}

// NewProjectChangePinnedResponseWithDefaults instantiates a new ProjectChangePinnedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectChangePinnedResponseWithDefaults() *ProjectChangePinnedResponse {
	this := ProjectChangePinnedResponse{}
	return &this
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *ProjectChangePinnedResponse) GetProject() ProjectProject {
	if o == nil || isNil(o.Project) {
		var ret ProjectProject
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectChangePinnedResponse) GetProjectOk() (*ProjectProject, bool) {
	if o == nil || isNil(o.Project) {
    return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *ProjectChangePinnedResponse) HasProject() bool {
	if o != nil && !isNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given ProjectProject and assigns it to the Project field.
func (o *ProjectChangePinnedResponse) SetProject(v ProjectProject) {
	o.Project = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ProjectChangePinnedResponse) GetError() ProjectChangePinnedResponseError {
	if o == nil || isNil(o.Error) {
		var ret ProjectChangePinnedResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectChangePinnedResponse) GetErrorOk() (*ProjectChangePinnedResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ProjectChangePinnedResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ProjectChangePinnedResponseError and assigns it to the Error field.
func (o *ProjectChangePinnedResponse) SetError(v ProjectChangePinnedResponseError) {
	o.Error = &v
}

func (o ProjectChangePinnedResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableProjectChangePinnedResponse struct {
	value *ProjectChangePinnedResponse
	isSet bool
}

func (v NullableProjectChangePinnedResponse) Get() *ProjectChangePinnedResponse {
	return v.value
}

func (v *NullableProjectChangePinnedResponse) Set(val *ProjectChangePinnedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectChangePinnedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectChangePinnedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectChangePinnedResponse(val *ProjectChangePinnedResponse) *NullableProjectChangePinnedResponse {
	return &NullableProjectChangePinnedResponse{value: val, isSet: true}
}

func (v NullableProjectChangePinnedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectChangePinnedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


