/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails{}

// CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails struct for CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails
type CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails struct {
	ServiceUuid *string `json:"service_uuid,omitempty"`
	ServiceType *string `json:"service_type,omitempty"`
}

// NewCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails instantiates a new CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails() *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails {
	this := CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails{}
	return &this
}

// NewCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetailsWithDefaults instantiates a new CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetailsWithDefaults() *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails {
	this := CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails{}
	return &this
}

// GetServiceUuid returns the ServiceUuid field value if set, zero value otherwise.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) GetServiceUuid() string {
	if o == nil || IsNil(o.ServiceUuid) {
		var ret string
		return ret
	}
	return *o.ServiceUuid
}

// GetServiceUuidOk returns a tuple with the ServiceUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) GetServiceUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceUuid) {
		return nil, false
	}
	return o.ServiceUuid, true
}

// HasServiceUuid returns a boolean if a field has been set.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) HasServiceUuid() bool {
	if o != nil && !IsNil(o.ServiceUuid) {
		return true
	}

	return false
}

// SetServiceUuid gets a reference to the given string and assigns it to the ServiceUuid field.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) SetServiceUuid(v string) {
	o.ServiceUuid = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) SetServiceType(v string) {
	o.ServiceType = &v
}

func (o CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceUuid) {
		toSerialize["service_uuid"] = o.ServiceUuid
	}
	if !IsNil(o.ServiceType) {
		toSerialize["service_type"] = o.ServiceType
	}
	return toSerialize, nil
}

type NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails struct {
	value *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails
	isSet bool
}

func (v NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) Get() *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails {
	return v.value
}

func (v *NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) Set(val *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails(val *CdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) *NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails {
	return &NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails{value: val, isSet: true}
}

func (v NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnCdnCreateErrorDomainErrorDomainAlreadyUsedDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


