/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// ProjectChangePinnedRequest struct for ProjectChangePinnedRequest
type ProjectChangePinnedRequest struct {
	ProjectId *string `json:"project_id,omitempty"`
	UiPinned *bool `json:"ui_pinned,omitempty"`
}

// NewProjectChangePinnedRequest instantiates a new ProjectChangePinnedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectChangePinnedRequest() *ProjectChangePinnedRequest {
	this := ProjectChangePinnedRequest{}
	return &this
}

// NewProjectChangePinnedRequestWithDefaults instantiates a new ProjectChangePinnedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectChangePinnedRequestWithDefaults() *ProjectChangePinnedRequest {
	this := ProjectChangePinnedRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ProjectChangePinnedRequest) GetProjectId() string {
	if o == nil || isNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectChangePinnedRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || isNil(o.ProjectId) {
    return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ProjectChangePinnedRequest) HasProjectId() bool {
	if o != nil && !isNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *ProjectChangePinnedRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetUiPinned returns the UiPinned field value if set, zero value otherwise.
func (o *ProjectChangePinnedRequest) GetUiPinned() bool {
	if o == nil || isNil(o.UiPinned) {
		var ret bool
		return ret
	}
	return *o.UiPinned
}

// GetUiPinnedOk returns a tuple with the UiPinned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectChangePinnedRequest) GetUiPinnedOk() (*bool, bool) {
	if o == nil || isNil(o.UiPinned) {
    return nil, false
	}
	return o.UiPinned, true
}

// HasUiPinned returns a boolean if a field has been set.
func (o *ProjectChangePinnedRequest) HasUiPinned() bool {
	if o != nil && !isNil(o.UiPinned) {
		return true
	}

	return false
}

// SetUiPinned gets a reference to the given bool and assigns it to the UiPinned field.
func (o *ProjectChangePinnedRequest) SetUiPinned(v bool) {
	o.UiPinned = &v
}

func (o ProjectChangePinnedRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !isNil(o.UiPinned) {
		toSerialize["ui_pinned"] = o.UiPinned
	}
	return json.Marshal(toSerialize)
}

type NullableProjectChangePinnedRequest struct {
	value *ProjectChangePinnedRequest
	isSet bool
}

func (v NullableProjectChangePinnedRequest) Get() *ProjectChangePinnedRequest {
	return v.value
}

func (v *NullableProjectChangePinnedRequest) Set(val *ProjectChangePinnedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectChangePinnedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectChangePinnedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectChangePinnedRequest(val *ProjectChangePinnedRequest) *NullableProjectChangePinnedRequest {
	return &NullableProjectChangePinnedRequest{value: val, isSet: true}
}

func (v NullableProjectChangePinnedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectChangePinnedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


