/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the MysqlStatisticGetDiskUsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MysqlStatisticGetDiskUsageResponse{}

// MysqlStatisticGetDiskUsageResponse struct for MysqlStatisticGetDiskUsageResponse
type MysqlStatisticGetDiskUsageResponse struct {
	DiskUsage *StructuresStatisticSeriesData `json:"disk_usage,omitempty"`
}

// NewMysqlStatisticGetDiskUsageResponse instantiates a new MysqlStatisticGetDiskUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlStatisticGetDiskUsageResponse() *MysqlStatisticGetDiskUsageResponse {
	this := MysqlStatisticGetDiskUsageResponse{}
	return &this
}

// NewMysqlStatisticGetDiskUsageResponseWithDefaults instantiates a new MysqlStatisticGetDiskUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlStatisticGetDiskUsageResponseWithDefaults() *MysqlStatisticGetDiskUsageResponse {
	this := MysqlStatisticGetDiskUsageResponse{}
	return &this
}

// GetDiskUsage returns the DiskUsage field value if set, zero value otherwise.
func (o *MysqlStatisticGetDiskUsageResponse) GetDiskUsage() StructuresStatisticSeriesData {
	if o == nil || IsNil(o.DiskUsage) {
		var ret StructuresStatisticSeriesData
		return ret
	}
	return *o.DiskUsage
}

// GetDiskUsageOk returns a tuple with the DiskUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MysqlStatisticGetDiskUsageResponse) GetDiskUsageOk() (*StructuresStatisticSeriesData, bool) {
	if o == nil || IsNil(o.DiskUsage) {
		return nil, false
	}
	return o.DiskUsage, true
}

// HasDiskUsage returns a boolean if a field has been set.
func (o *MysqlStatisticGetDiskUsageResponse) HasDiskUsage() bool {
	if o != nil && !IsNil(o.DiskUsage) {
		return true
	}

	return false
}

// SetDiskUsage gets a reference to the given StructuresStatisticSeriesData and assigns it to the DiskUsage field.
func (o *MysqlStatisticGetDiskUsageResponse) SetDiskUsage(v StructuresStatisticSeriesData) {
	o.DiskUsage = &v
}

func (o MysqlStatisticGetDiskUsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MysqlStatisticGetDiskUsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiskUsage) {
		toSerialize["disk_usage"] = o.DiskUsage
	}
	return toSerialize, nil
}

type NullableMysqlStatisticGetDiskUsageResponse struct {
	value *MysqlStatisticGetDiskUsageResponse
	isSet bool
}

func (v NullableMysqlStatisticGetDiskUsageResponse) Get() *MysqlStatisticGetDiskUsageResponse {
	return v.value
}

func (v *NullableMysqlStatisticGetDiskUsageResponse) Set(val *MysqlStatisticGetDiskUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlStatisticGetDiskUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlStatisticGetDiskUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlStatisticGetDiskUsageResponse(val *MysqlStatisticGetDiskUsageResponse) *NullableMysqlStatisticGetDiskUsageResponse {
	return &NullableMysqlStatisticGetDiskUsageResponse{value: val, isSet: true}
}

func (v NullableMysqlStatisticGetDiskUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlStatisticGetDiskUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


