/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// CdnSettingsStaticResponseHeaderHeader struct for CdnSettingsStaticResponseHeaderHeader
type CdnSettingsStaticResponseHeaderHeader struct {
	Name *string `json:"name,omitempty"`
	Value []string `json:"value,omitempty"`
	Always *bool `json:"always,omitempty"`
}

// NewCdnSettingsStaticResponseHeaderHeader instantiates a new CdnSettingsStaticResponseHeaderHeader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnSettingsStaticResponseHeaderHeader() *CdnSettingsStaticResponseHeaderHeader {
	this := CdnSettingsStaticResponseHeaderHeader{}
	return &this
}

// NewCdnSettingsStaticResponseHeaderHeaderWithDefaults instantiates a new CdnSettingsStaticResponseHeaderHeader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnSettingsStaticResponseHeaderHeaderWithDefaults() *CdnSettingsStaticResponseHeaderHeader {
	this := CdnSettingsStaticResponseHeaderHeader{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CdnSettingsStaticResponseHeaderHeader) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsStaticResponseHeaderHeader) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CdnSettingsStaticResponseHeaderHeader) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CdnSettingsStaticResponseHeaderHeader) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CdnSettingsStaticResponseHeaderHeader) GetValue() []string {
	if o == nil || isNil(o.Value) {
		var ret []string
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsStaticResponseHeaderHeader) GetValueOk() ([]string, bool) {
	if o == nil || isNil(o.Value) {
    return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CdnSettingsStaticResponseHeaderHeader) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []string and assigns it to the Value field.
func (o *CdnSettingsStaticResponseHeaderHeader) SetValue(v []string) {
	o.Value = v
}

// GetAlways returns the Always field value if set, zero value otherwise.
func (o *CdnSettingsStaticResponseHeaderHeader) GetAlways() bool {
	if o == nil || isNil(o.Always) {
		var ret bool
		return ret
	}
	return *o.Always
}

// GetAlwaysOk returns a tuple with the Always field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnSettingsStaticResponseHeaderHeader) GetAlwaysOk() (*bool, bool) {
	if o == nil || isNil(o.Always) {
    return nil, false
	}
	return o.Always, true
}

// HasAlways returns a boolean if a field has been set.
func (o *CdnSettingsStaticResponseHeaderHeader) HasAlways() bool {
	if o != nil && !isNil(o.Always) {
		return true
	}

	return false
}

// SetAlways gets a reference to the given bool and assigns it to the Always field.
func (o *CdnSettingsStaticResponseHeaderHeader) SetAlways(v bool) {
	o.Always = &v
}

func (o CdnSettingsStaticResponseHeaderHeader) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !isNil(o.Always) {
		toSerialize["always"] = o.Always
	}
	return json.Marshal(toSerialize)
}

type NullableCdnSettingsStaticResponseHeaderHeader struct {
	value *CdnSettingsStaticResponseHeaderHeader
	isSet bool
}

func (v NullableCdnSettingsStaticResponseHeaderHeader) Get() *CdnSettingsStaticResponseHeaderHeader {
	return v.value
}

func (v *NullableCdnSettingsStaticResponseHeaderHeader) Set(val *CdnSettingsStaticResponseHeaderHeader) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnSettingsStaticResponseHeaderHeader) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnSettingsStaticResponseHeaderHeader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnSettingsStaticResponseHeaderHeader(val *CdnSettingsStaticResponseHeaderHeader) *NullableCdnSettingsStaticResponseHeaderHeader {
	return &NullableCdnSettingsStaticResponseHeaderHeader{value: val, isSet: true}
}

func (v NullableCdnSettingsStaticResponseHeaderHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnSettingsStaticResponseHeaderHeader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


