/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the S3ChangeDomainResponseErrorDomainAlreadyUsedDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3ChangeDomainResponseErrorDomainAlreadyUsedDetails{}

// S3ChangeDomainResponseErrorDomainAlreadyUsedDetails struct for S3ChangeDomainResponseErrorDomainAlreadyUsedDetails
type S3ChangeDomainResponseErrorDomainAlreadyUsedDetails struct {
	ServiceUuid *string `json:"service_uuid,omitempty"`
	ServiceType *string `json:"service_type,omitempty"`
}

// NewS3ChangeDomainResponseErrorDomainAlreadyUsedDetails instantiates a new S3ChangeDomainResponseErrorDomainAlreadyUsedDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3ChangeDomainResponseErrorDomainAlreadyUsedDetails() *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails {
	this := S3ChangeDomainResponseErrorDomainAlreadyUsedDetails{}
	return &this
}

// NewS3ChangeDomainResponseErrorDomainAlreadyUsedDetailsWithDefaults instantiates a new S3ChangeDomainResponseErrorDomainAlreadyUsedDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3ChangeDomainResponseErrorDomainAlreadyUsedDetailsWithDefaults() *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails {
	this := S3ChangeDomainResponseErrorDomainAlreadyUsedDetails{}
	return &this
}

// GetServiceUuid returns the ServiceUuid field value if set, zero value otherwise.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) GetServiceUuid() string {
	if o == nil || IsNil(o.ServiceUuid) {
		var ret string
		return ret
	}
	return *o.ServiceUuid
}

// GetServiceUuidOk returns a tuple with the ServiceUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) GetServiceUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceUuid) {
		return nil, false
	}
	return o.ServiceUuid, true
}

// HasServiceUuid returns a boolean if a field has been set.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) HasServiceUuid() bool {
	if o != nil && !IsNil(o.ServiceUuid) {
		return true
	}

	return false
}

// SetServiceUuid gets a reference to the given string and assigns it to the ServiceUuid field.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) SetServiceUuid(v string) {
	o.ServiceUuid = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) SetServiceType(v string) {
	o.ServiceType = &v
}

func (o S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceUuid) {
		toSerialize["service_uuid"] = o.ServiceUuid
	}
	if !IsNil(o.ServiceType) {
		toSerialize["service_type"] = o.ServiceType
	}
	return toSerialize, nil
}

type NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails struct {
	value *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails
	isSet bool
}

func (v NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails) Get() *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails {
	return v.value
}

func (v *NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails) Set(val *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails(val *S3ChangeDomainResponseErrorDomainAlreadyUsedDetails) *NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails {
	return &NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails{value: val, isSet: true}
}

func (v NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3ChangeDomainResponseErrorDomainAlreadyUsedDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


