/*
API Управляемых сервисов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.6.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiCloud

import (
	"encoding/json"
)

// checks if the NetworkDriveUnmountResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkDriveUnmountResponseError{}

// NetworkDriveUnmountResponseError struct for NetworkDriveUnmountResponseError
type NetworkDriveUnmountResponseError struct {
	Message *string `json:"message,omitempty"`
	Code *string `json:"code,omitempty"`
}

// NewNetworkDriveUnmountResponseError instantiates a new NetworkDriveUnmountResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkDriveUnmountResponseError() *NetworkDriveUnmountResponseError {
	this := NetworkDriveUnmountResponseError{}
	return &this
}

// NewNetworkDriveUnmountResponseErrorWithDefaults instantiates a new NetworkDriveUnmountResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkDriveUnmountResponseErrorWithDefaults() *NetworkDriveUnmountResponseError {
	this := NetworkDriveUnmountResponseError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NetworkDriveUnmountResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveUnmountResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NetworkDriveUnmountResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NetworkDriveUnmountResponseError) SetMessage(v string) {
	o.Message = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *NetworkDriveUnmountResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDriveUnmountResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *NetworkDriveUnmountResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *NetworkDriveUnmountResponseError) SetCode(v string) {
	o.Code = &v
}

func (o NetworkDriveUnmountResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkDriveUnmountResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableNetworkDriveUnmountResponseError struct {
	value *NetworkDriveUnmountResponseError
	isSet bool
}

func (v NullableNetworkDriveUnmountResponseError) Get() *NetworkDriveUnmountResponseError {
	return v.value
}

func (v *NullableNetworkDriveUnmountResponseError) Set(val *NetworkDriveUnmountResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkDriveUnmountResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkDriveUnmountResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkDriveUnmountResponseError(val *NetworkDriveUnmountResponseError) *NullableNetworkDriveUnmountResponseError {
	return &NullableNetworkDriveUnmountResponseError{value: val, isSet: true}
}

func (v NullableNetworkDriveUnmountResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkDriveUnmountResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


